'use client';
import {useRef,useState} from 'react';
import {SAMPLE_ROWS} from '@/lib/readyTools/catalog.mjs';
import {parseTable,toCSV} from '@/lib/readyTools/data.mjs';
import {importFile,saveFile} from '@/lib/readyTools/files.mjs';
import {Icon,Button,Notice} from './ui';
export default function DatasetInput({rows,onData,disabled}){
 const [mode,setMode]=useState('file'),[paste,setPaste]=useState(''),[drag,setDrag]=useState(false),[reading,setReading]=useState(false),[error,setError]=useState(''),[book,setBook]=useState(null),[sheet,setSheet]=useState(0),[name,setName]=useState('');const input=useRef(null);
 async function read(file){if(!file||disabled||reading)return;setReading(true);setError('');try{const data=await importFile(file);setBook(data.book);setSheet(0);setName(file.name);onData(data.rows,{name:file.name,note:data.book?.note||'',sample:false});}catch(e){setError(e.message);}finally{setReading(false);}}
 return <div className="rt-input-area"><div className="rt-input-tabs"><button className={mode==='file'?'active':''} onClick={()=>setMode('file')}><Icon name="Upload" size={15}/>Upload a file</button><button className={mode==='paste'?'active':''} onClick={()=>setMode('paste')}><Icon name="ClipboardPaste" size={15}/>Paste a table</button></div>
  {mode==='file'?<div className={`rt-dropzone ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);read(e.dataTransfer.files?.[0]);}}><input ref={input} type="file" accept=".csv,.tsv,.json,.xlsx" aria-label="Choose CSV Excel or JSON file" className="rt-sr-only" disabled={disabled||reading} onChange={e=>{read(e.target.files?.[0]);e.target.value='';}}/><span className="rt-upload-icon"><Icon name={reading?'Loader2':'FileUp'} size={30} className={reading?'rt-spin':''}/></span><h3>{reading?'Reading your file…':'Drop your file. Skip the busywork.'}</h3><p>CSV, Excel (.xlsx), TSV or JSON · up to 5 MB</p><Button icon="FolderOpen" disabled={disabled||reading} onClick={()=>input.current?.click()}>Browse files</Button><small>Up to 10,000 rows, 100 columns and 300,000 cells.</small></div>:<div className="rt-paste"><label htmlFor="rt-paste-input">Paste copied Excel cells, CSV, or a JSON list</label><textarea id="rt-paste-input" value={paste} disabled={disabled} onChange={e=>setPaste(e.target.value)} rows={8} maxLength={5*1024*1024} placeholder={'name,email,score\nAyesha,ayesha@example.com,92\nAli,ali@example.com,72'}/><Button icon="Table2" disabled={disabled||!paste.trim()} onClick={()=>{try{const value=parseTable(paste);setBook(null);setName('Pasted table');onData(value,{name:'Pasted table',sample:false});setError('');}catch(e){setError(e.message);}}}>Use this data</Button></div>}
  <div className="rt-input-helper"><span>Just exploring?</span><Button variant="link" disabled={disabled||reading} onClick={()=>{setBook(null);setName('Example dataset');onData(SAMPLE_ROWS.map(r=>({...r})),{name:'Example dataset',sample:true});setError('');}}>Try example data <Icon name="ArrowRight" size={14}/></Button><Button variant="icon ghost" icon="Download" title="Download sample CSV" aria-label="Download sample CSV" onClick={()=>saveFile(toCSV(SAMPLE_ROWS),'multimind-example.csv','text/csv;charset=utf-8')}/></div>
  {error&&<Notice kind="error">{error}</Notice>}
  {book&&<label className="rt-field">Worksheet<select value={sheet} disabled={disabled||reading} onChange={async e=>{const index=Number(e.target.value);setReading(true);try{const value=await book.loadSheet(index);setSheet(index);onData(value,{name:`${name} · ${book.sheets[index].name}`,note:book.note,sample:false});setError('');}catch(e){setError(e.message);}finally{setReading(false);}}}>{book.sheets.map((s,i)=><option key={s.path} value={i}>{s.name}</option>)}</select></label>}
  {rows.length>0&&<div className="rt-input-preview"><div><span className="rt-pill success"><Icon name="Check" size={12}/>{rows.length.toLocaleString()} records loaded</span><span>{Object.keys(rows[0]).length} columns</span></div><div className="rt-table-scroll"><table className="rt-table"><thead><tr>{Object.keys(rows[0]).slice(0,6).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,4).map((r,i)=><tr key={i}>{Object.keys(rows[0]).slice(0,6).map(c=><td key={c} title={String(r[c]??'')}>{String(r[c]??'')}</td>)}</tr>)}</tbody></table></div><small>Previewing the first {Math.min(4,rows.length)} rows{Object.keys(rows[0]).length>6?' and 6 columns':''}. All loaded records are used.</small></div>}
 </div>;
}
