'use client';
import {Icon,Button} from './ui';
export function Field({label,value,onChange,options,type='text',hint,...props}){return <label className="rt-field"><span>{label}</span>{options?<select value={value??''} onChange={e=>onChange(e.target.value)} {...props}>{options.map(o=>{const item=typeof o==='string'?{value:o,label:o}:o;return <option value={item.value} key={item.value}>{item.label}</option>;})}</select>:<input type={type} value={value??''} onChange={e=>onChange(e.target.value)} {...props}/>} {hint&&<small>{hint}</small>}</label>;}
function Check({label,checked,onChange,hint}){return <label className="rt-check"><input type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)}/><span>{label}{hint&&<small>{hint}</small>}</span></label>;}
export default function OptionsForm({tool,rows,options:o,onChange}){
 const columns=Object.keys(rows[0]||{}),set=(key,value)=>onChange({...o,[key]:value}),columnOptions=[{value:'',label:'None / automatic'},...columns.map(c=>({value:c,label:c}))];
 const column=(key,label,hint)=> <Field key={key} label={label} value={o[key]} options={columnOptions} onChange={v=>set(key,v)} hint={hint}/>;
 const flag=(key,label,hint)=> <Check key={key} label={label} checked={o[key]} onChange={v=>set(key,v)} hint={hint}/>;
 if(tool.engine==='connection')return null;
 if(tool.engine==='ai')return <div className="rt-fields-grid"><Field label="Tone" value={o.tone} onChange={v=>set('tone',v)} options={['Professional','Friendly','Confident','Simple','Formal']}/><Field label="Output language" value={o.language} onChange={v=>set('language',v)} options={['English','Urdu','Roman Urdu','Hindi','Arabic','Russian','Spanish','French','German','Turkish']}/><Field label="Length" value={o.length} onChange={v=>set('length',v)} options={['Concise','Balanced','Detailed']}/>{tool.id==='social-captions'&&<Field label="Platform" value={o.platform} onChange={v=>set('platform',v)} options={['Instagram','LinkedIn','Facebook','TikTok','YouTube','X']}/>}</div>;
 if(tool.id==='text-cleaner')return <div className="rt-options-stack">{flag('removeBlankLines','Remove empty lines')}{flag('removeDuplicateLines','Remove duplicate lines')}{flag('ignoreCase','Ignore case when comparing lines')}<Field label="Letter case" value={o.letterCase} options={[{value:'keep',label:'Keep original'},{value:'lower',label:'lowercase'},{value:'upper',label:'UPPERCASE'}]} onChange={v=>set('letterCase',v)}/></div>;
 if(tool.id==='json-formatter')return flag('compact','Produce compact JSON');
 if(tool.id==='text-stats')return <p className="rt-muted">No extra setup. Word count uses whitespace boundaries; reading time assumes 200 words per minute.</p>;
 return <div className="rt-options-stack">
  {['clean-rank','remove-duplicates'].includes(tool.id)&&column('duplicateColumn','Match duplicates by','None compares all columns. The first matching record is kept; blank keys stay distinct.')}
  {tool.id==='email-cleaner'&&column('emailColumn','Email column','Choose the column that contains email addresses.')}
  {['clean-rank','filter-sort'].includes(tool.id)&&<><div className="rt-fields-grid">{column('rankColumn','Sort / rank column')}<Field label="Order" value={o.direction} options={[{value:'desc',label:'Highest / Z first'},{value:'asc',label:'Lowest / A first'}]} onChange={v=>set('direction',v)}/></div>{tool.id==='clean-rank'&&<Field label="Minimum score" type="number" value={o.minScore} onChange={v=>set('minScore',v)} hint="Leave blank to keep all scores. Only applied when a ranking column is selected."/>}<Field label="Maximum result rows" type="number" min={1} max={10000} value={o.limit} onChange={v=>set('limit',v)}/></>}
  {tool.id==='filter-sort'&&<><div className="rt-fields-grid">{column('filterColumn','Filter column')}<Field label="Condition" value={o.operator} options={[{value:'contains',label:'Contains'},{value:'equals',label:'Equals'},{value:'not-equals',label:'Does not equal'},{value:'gte',label:'Number ≥'},{value:'lte',label:'Number ≤'},{value:'empty',label:'Is empty'},{value:'not-empty',label:'Is not empty'}]} onChange={v=>set('operator',v)}/></div>{!['empty','not-empty'].includes(o.operator)&&<Field label="Match value" value={o.filterValue} maxLength={200} onChange={v=>set('filterValue',v)}/>}</>}
  {tool.id==='data-summary'&&<><div className="rt-fields-grid">{column('groupColumn','Group by (optional)','Leave blank for per-column statistics.')}{column('valueColumn','Numeric column to total','Needed only when you choose a group.')}</div></>}
  {tool.id==='column-picker'&&<div className="rt-column-options"><p className="rt-muted">Select columns, rename headers and use arrows to change their order.</p>{(o.columns||[]).map((c,i)=><div className="rt-column-row" key={c}><Check label={c} checked onChange={()=>set('columns',o.columns.filter(v=>v!==c))}/><input aria-label={`Rename ${c}`} value={o.renames?.[c]??c} maxLength={200} onChange={e=>set('renames',{...o.renames,[c]:e.target.value})}/><Button icon="ArrowUp" variant="icon ghost" aria-label={`Move ${c} up`} disabled={i===0} onClick={()=>{const next=[...o.columns];[next[i-1],next[i]]=[next[i],next[i-1]];set('columns',next);}}/><Button icon="ArrowDown" variant="icon ghost" aria-label={`Move ${c} down`} disabled={i===o.columns.length-1} onClick={()=>{const next=[...o.columns];[next[i+1],next[i]]=[next[i],next[i+1]];set('columns',next);}}/></div>)}{columns.filter(c=>!o.columns?.includes(c)).map(c=><Check key={c} label={c} checked={false} onChange={()=>set('columns',[...(o.columns||[]),c])}/>)}</div>}
  {tool.id==='format-converter'&&<p className="rt-muted">Run once, then use the CSV, Excel or JSON download buttons in your result. Formatting, macros and formulas are not carried into the new file.</p>}
  {flag('trim','Trim spaces around cell values')}
  {['clean-rank','remove-duplicates','email-cleaner','filter-sort'].includes(tool.id)&&flag('ignoreCase','Ignore upper/lowercase when matching','For example: AYESHA and Ayesha are treated as the same value.')}
 </div>;
}
