'use client';
import {useEffect,useMemo,useState} from 'react';
import {toCSV} from '@/lib/readyTools/data.mjs';
import {downloadResult} from '@/lib/readyTools/files.mjs';
import {Button,Icon,Notice} from './ui';
export default function ResultView({result,tool,defaultExport='csv',onTransfer,compatible=[],stale=false}){
 const[view,setView]=useState('table'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[sort,setSort]=useState(null),[copied,setCopied]=useState(false),[error,setError]=useState(''),[downloading,setDownloading]=useState(false),[source,setSource]=useState('result');
 useEffect(()=>{setView('table');setQuery('');setPage(0);setSort(null);setSource('result');setError('');},[result]);
 const rows=source==='excluded'?result.excluded||[]:result.rows||[],columns=useMemo(()=>[...new Set(rows.flatMap(Object.keys))],[rows]);
 const filtered=useMemo(()=>{const found=rows.filter(r=>!query||Object.values(r).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase())));if(sort)found.sort((a,b)=>{const x=a[sort.column],y=b[sort.column];const cmp=typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??''),undefined,{numeric:true});return sort.direction*cmp;});return found;},[rows,query,sort]);
 const maxPage=Math.max(0,Math.ceil(filtered.length/25)-1),current=Math.min(page,maxPage),pageRows=filtered.slice(current*25,current*25+25);
 async function download(format){setDownloading(true);setError('');try{await downloadResult(source==='excluded'?{...result,rows}:result,format,`${tool.id}${source==='excluded'?'-removed':''}`);}catch(e){setError(e.message);}finally{setDownloading(false);}}
 async function copy(){try{await navigator.clipboard.writeText(result.kind==='table'?(view==='json'?JSON.stringify(rows,null,2):toCSV(rows,{bom:false})):result.text);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setError('Clipboard access was blocked. Use a download button instead.');}}
 return <section className="rt-result" aria-label="Tool results">
  <div className="rt-result-heading"><div><span className="rt-success-icon"><Icon name="Check" size={22}/></span><div><h2>Your result is ready.</h2><p>{result.durationMs!=null?`Finished in ${(result.durationMs/1000).toFixed(2)}s. `:''}Review it before using or sharing.</p></div></div><Button icon={copied?'Check':'Copy'} onClick={copy}>{copied?'Copied':'Copy result'}</Button></div>
  {stale&&<Notice>Inputs or options changed. This is the previous result; run the tool again to update it.</Notice>}
  <div className="rt-result-stats">{(result.stats||[]).slice(0,6).map((s,i)=><div key={`${s.label}-${i}`}><span>{s.label}</span><strong>{String(s.value)}</strong></div>)}</div>
  {result.report?.warnings?.length>0&&<div className="rt-result-warnings">{result.report.warnings.map((w,i)=><Notice key={i} kind="warning">{w}</Notice>)}</div>}
  {error&&<Notice kind="error">{error}</Notice>}
  <div className="rt-result-toolbar"><div className="rt-result-tabs">{result.kind==='table'&&<><button className={view==='table'?'active':''} onClick={()=>setView('table')}><Icon name="Table2" size={15}/>Table</button><button className={view==='json'?'active':''} onClick={()=>setView('json')}><Icon name="Braces" size={15}/>JSON</button>{result.excluded?.length>0&&<select aria-label="Review result or removed rows" value={source} onChange={e=>{setSource(e.target.value);setPage(0);}}><option value="result">Result rows</option><option value="excluded">Removed rows ({result.excluded.length})</option></select>}</>}</div><div className="rt-downloads"><Button icon="Download" variant="primary" disabled={downloading} onClick={()=>download(defaultExport)}>{downloading?'Preparing…':`Download ${result.kind==='table'?defaultExport.toUpperCase():result.fileType==='json'?'JSON':'text'}`}</Button>{result.kind==='table'&&<select aria-label="Other download formats" value="" disabled={downloading} onChange={e=>{if(e.target.value)download(e.target.value);}}><option value="">More formats</option><option value="csv">CSV</option><option value="xlsx">Excel (.xlsx)</option><option value="json">JSON</option></select>}</div></div>
  {result.kind==='table'?(view==='json'?<pre className="rt-result-text rt-code">{JSON.stringify(rows.slice(0,100),null,2)}{rows.length>100?'\n\nPreview limited to 100 records. Download or copy for all rows.':''}</pre>:<><label className="rt-search rt-table-search"><Icon name="Search" size={16}/><input placeholder="Search within this result…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} aria-label="Search result rows"/></label><div className="rt-table-scroll result"><table className="rt-table"><thead><tr><th className="rt-row-number">#</th>{columns.map(c=><th key={c} aria-sort={sort?.column===c?(sort.direction===1?'ascending':'descending'):'none'}><button onClick={()=>setSort({column:c,direction:sort?.column===c?-sort.direction:1})}>{c}<Icon name={sort?.column===c?(sort.direction===1?'ArrowUp':'ArrowDown'):'ChevronsUpDown'} size={12}/></button></th>)}</tr></thead><tbody>{pageRows.map((r,i)=><tr key={i}><td className="rt-row-number">{current*25+i+1}</td>{columns.map(c=><td key={c} title={String(r[c]??'')}>{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'')}</td>)}</tr>)}</tbody></table>{!pageRows.length&&<div className="rt-empty compact"><Icon name="ListFilter" size={24}/><p>{rows.length?'No rows match that search.':'No rows matched the selected conditions. Review the options or removed rows.'}</p></div>}</div><div className="rt-pagination"><span>{filtered.length?`${current*25+1}–${Math.min((current+1)*25,filtered.length)}`:'0'} of {filtered.length.toLocaleString()} rows{query?' matching search':''}</span><div><Button icon="ChevronLeft" variant="icon ghost" disabled={!current} aria-label="Previous result page" onClick={()=>setPage(Math.max(0,current-1))}/><span>{current+1} / {maxPage+1}</span><Button icon="ChevronRight" variant="icon ghost" disabled={current>=maxPage} aria-label="Next result page" onClick={()=>setPage(current+1)}/></div></div><p className="rt-fine-print">Downloads and Copy include all {source==='excluded'?'removed':'result'} rows, not only the current table search or page. Table sorting is a preview control.</p></>):<pre className="rt-result-text">{result.text}</pre>}
  <div className="rt-result-bottom"><details><summary><Icon name="ListChecks" size={16}/>What happened?<Icon name="ChevronDown" size={14}/></summary><ol>{(result.report?.steps||['Processed the supplied input']).map((step,i)=><li key={i}><Icon name="Check" size={14}/>{step}</li>)}</ol></details>{compatible.length>0&&<label className="rt-chain-select"><Icon name="ArrowRightLeft" size={17}/><select aria-label="Use result in another tool" value="" onChange={e=>{if(e.target.value)onTransfer(e.target.value);}}><option value="">Use result in another tool…</option>{compatible.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}</div>
 </section>;
}
