'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {TOOLS,CATEGORIES,getTool} from '@/lib/readyTools/catalog.mjs';
import {ToolShell,Icon,Button,Notice,useWorkspace,timeLabel} from './ui';
export default function ToolHub(){
 const[query,setQuery]=useState(''),[category,setCategory]=useState('All tools'),[view,setView]=useState('library'),[toast,setToast]=useState('');const {workspace,update,error,loading,reload}=useWorkspace();
 const visible=useMemo(()=>TOOLS.filter(t=>(category==='All tools'||t.category===category)&&(view!=='favorites'||workspace.favorites.includes(t.id))&&`${t.name} ${t.description} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[category,query,view,workspace.favorites]);
 async function star(id){try{await update({action:'favorite',toolId:id,value:!workspace.favorites.includes(id)});setToast('');}catch(e){setToast(e.message);}}
 const localCount=TOOLS.filter(t=>t.engine==='local').length;
 return <ToolShell aside={<><p className="rt-nav-heading">YOUR SPACE</p><button className={`rt-nav-link ${view==='favorites'?'selected':''}`} onClick={()=>{setView('favorites');setCategory('All tools');}}><Icon name="Star"/>Favorites<span className="rt-nav-count">{workspace.favorites.length}</span></button><button className={`rt-nav-link ${view==='recent'?'selected':''}`} onClick={()=>setView('recent')}><Icon name="History"/>Recent activity<span className="rt-nav-count">{workspace.recent.length}</span></button></>}>
  <main className="rt-content">
   <section className="rt-hero"><div className="rt-hero-copy"><div className="rt-eyebrow"><span className="rt-dot"/> YOUR EVERYDAY TOOLKIT, UPGRADED</div><h1>Big results.<br/><span>Small effort.</span></h1><p>Clean a dataset. Polish your writing. Get the next task done.<br className="rt-wide-only"/> Ready-made tools that work the way you do.</p><div className="rt-hero-actions"><Link href="/dashboard/flows/tools/clean-rank" className="rt-button primary">Try the data cleaner <Icon name="ArrowUpRight" size={17}/></Link><Link href="/dashboard/flows/workflows" className="rt-text-link">Open advanced builder <Icon name="ArrowRight" size={15}/></Link></div><div className="rt-trustline"><span><Icon name="Check" size={14}/>No nodes to connect</span><span><Icon name="Check" size={14}/>Preview before download</span></div></div>
    <div className="rt-hero-preview" aria-label="Example data cleaning result"><div className="rt-preview-bar"><div className="rt-three-dots"><i/><i/><i/></div><span>Clean & rank · example</span><span className="rt-pill success"><Icon name="Check" size={12}/>Ready</span></div><div className="rt-preview-pipeline">{[['FileSpreadsheet','Your file'],['ListFilter','Clean & rank'],['CircleCheck','Your result']].map(([icon,label],i)=><div className="rt-pipeline-part" key={label}>{i>0&&<span className="rt-pipeline-line"/>}<div><span className={`rt-pipeline-icon stage-${i}`}><Icon name={icon} size={22}/></span><small>{label}</small></div></div>)}</div><div className="rt-preview-table"><div className="rt-preview-table-head"><span>CONTACT</span><span>SCORE</span></div>{[['AK','Ayesha Khan',92],['UM','Usman Malik',88],['AR','Ali Raza',72]].map(([initial,name,score])=><div className="rt-preview-table-row" key={name}><div><span className="rt-mini-avatar">{initial}</span>{name}</div><strong>{score}<span className="rt-score-bar" style={{width:`${score*0.48}px`}}/></strong></div>)}</div><div className="rt-preview-footer"><span><Icon name="ShieldCheck" size={15}/>Original file untouched</span><span>6 in → 4 out</span></div></div>
   </section>
   <section className="rt-overview" aria-label="Toolkit capabilities">{[[TOOLS.length,'ready-made tools','LayoutGrid'],[localCount,'browser-only utilities','ShieldCheck'],['01','place for connections','Plug'],['03','steps: add, run, download','ArrowRight']].map(([v,label,icon])=><div key={label}><span className="rt-overview-icon"><Icon name={icon} size={20}/></span><div><strong>{v}</strong><span>{label}</span></div></div>)}</section>
   {(toast||error)&&<Notice kind="error">{toast||error} <button onClick={reload} className="rt-inline-button">Retry workspace sync</button>. Browser-only tools can still process data.</Notice>}
   <div className="rt-section-heading"><div><div className="rt-eyebrow">FIND YOUR NEXT SHORTCUT</div><h2>{view==='recent'?'Your recent activity':view==='favorites'?'Your favorite tools':'What would you like to do?'}</h2></div><div className="rt-view-tabs">{[['library','LayoutGrid','Library'],['favorites','Star','Favorites'],['recent','History','Recent']].map(([key,icon,label])=><Button key={key} icon={icon} variant={view===key?'selected':'ghost'} onClick={()=>setView(key)}>{label}</Button>)}</div></div>
   {view!=='recent'?<><div className="rt-toolbar"><label className="rt-search"><Icon name="Search" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tools, tasks, or file types…" aria-label="Search ready-made tools"/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><Icon name="X" size={16}/></button>}</label><span className="rt-result-count">{visible.length} tools</span></div><nav className="rt-category-tabs" aria-label="Tool categories">{CATEGORIES.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}<small>{TOOLS.filter(t=>c==='All tools'||t.category===c).length}</small></button>)}</nav>
   <div className="rt-tool-grid">{visible.map(tool=><article key={tool.id} className={`rt-tool-card ${tool.featured?'featured':''}`}><div className="rt-card-top"><span className={`rt-tool-icon ${tool.engine}`}><Icon name={tool.icon} size={23}/></span><Button icon="Star" className={workspace.favorites.includes(tool.id)?'starred':''} variant="icon ghost" aria-label={`${workspace.favorites.includes(tool.id)?'Remove':'Add'} ${tool.name} ${workspace.favorites.includes(tool.id)?'from':'to'} favorites`} aria-pressed={workspace.favorites.includes(tool.id)} onClick={()=>star(tool.id)}/></div><Link href={`/dashboard/flows/tools/${tool.id}`} className="rt-card-link"><div className="rt-card-title"><h3>{tool.name}</h3>{tool.featured&&<span className="rt-recommended">START HERE</span>}</div><p>{tool.description}</p><div className="rt-card-tags">{tool.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="rt-card-bottom"><span className={`rt-engine-label ${tool.engine}`}><Icon name={tool.engine==='local'?'ShieldCheck':tool.engine==='ai'?'Sparkles':'Plug'} size={13}/>{tool.engine==='local'?'Runs in your browser':tool.engine==='ai'?'Uses site AI credits':'Uses a saved connection'}</span><span className="rt-open-tool">Use tool <Icon name="ArrowUpRight" size={16}/></span></div></Link></article>)}</div>
   {!visible.length&&<div className="rt-empty"><span className="rt-empty-icon"><Icon name={view==='favorites'?'Star':'Search'} size={28}/></span><h3>{view==='favorites'?'Make this space yours.':'No matching tools yet.'}</h3><p>{view==='favorites'?'Star a tool in the library to keep it close.':'Try “data”, “email”, “summary”, or clear the filters.'}</p><Button onClick={()=>{setView('library');setQuery('');setCategory('All tools');}}>Show all tools</Button></div>}</>:
   <section className="rt-panel">{loading?<div className="rt-empty"><Icon name="Loader2" className="rt-spin"/>Loading activity…</div>:workspace.recent.length?<><div className="rt-panel-heading"><p>Metadata only: your input files and generated text are not saved here.</p><Button icon="Trash2" variant="ghost" onClick={async()=>{try{await update({action:'clear-history'});}catch{}}}>Clear activity</Button></div><div className="rt-activity-list">{workspace.recent.map((r,i)=>{const t=getTool(r.toolId);return <Link href={`/dashboard/flows/tools/${r.toolId}`} key={r.id||i}><span className="rt-tool-icon small"><Icon name={t?.icon||'Zap'} size={18}/></span><div><strong>{t?.name||r.toolId}</strong><small>{timeLabel(r.createdAt)}{r.rows?` · ${r.rows} result rows`:''}</small></div><span className={`rt-pill ${r.status==='success'?'success':'warning'}`}>{r.status}</span><Icon name="ArrowUpRight" size={16}/></Link>;})}</div></>:<div className="rt-empty"><span className="rt-empty-icon"><Icon name="History" size={28}/></span><h3>Your first win starts here.</h3><p>Run a tool and its activity will appear here. Results stay on the tool page, not in history.</p><Button onClick={()=>setView('library')} variant="primary">Explore the library</Button></div>}</section>}
   <section className="rt-bottom-callout"><span className="rt-tool-icon"><Icon name="Workflow" size={25}/></span><div><h3>Simple on the surface. Flexible underneath.</h3><p>Need branches, triggers, custom nodes or a multi-step automation? Your Flow Studio is still here.</p></div><Link className="rt-button" href="/dashboard/flows/workflows">Advanced workflows <Icon name="ArrowUpRight" size={15}/></Link></section>
   <details className="rt-help"><summary><Icon name="CircleHelp" size={17}/>How does this work?<Icon name="ChevronDown" size={15}/></summary><div><p><strong>1. Choose a tool.</strong> No workflow setup is required. Each tool has its own simple form.</p><p><strong>2. Add your data.</strong> Upload a table or paste text. Data utilities process it in this browser. AI and connected tools send the necessary content to the configured service.</p><p><strong>3. Run and review.</strong> Download your result or pass it to another tool. Sending a message always asks for confirmation. Settings controls themes, account connections and activity preferences.</p></div></details>
   <footer className="rt-page-footer"><span>Made for getting things done.</span><Link href="/dashboard/settings?tab=tools">Tool preferences <Icon name="ArrowUpRight" size={13}/></Link></footer>
  </main>
 </ToolShell>;
}
