'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useSession} from 'next-auth/react';
import {useSettings} from '@/lib/SettingsContext';
import {TOOLS,getTool,defaultOptions,SAMPLE_TEXT,LIMITS} from '@/lib/readyTools/catalog.mjs';
import {runLocalTool} from '@/lib/readyTools/local.mjs';
import {offerHandoff,takeHandoff} from '@/lib/readyTools/handoff.mjs';
import {ToolShell,Icon,Button,Notice,Dialog,request,useWorkspace,useCapabilities} from './ui';
import DatasetInput from './DatasetInput';
import OptionsForm,{Field} from './OptionsForm';
import ResultView from './ResultView';
export default function ToolRunner({toolId}){
 const tool=getTool(toolId),router=useRouter(),{data:session}=useSession(),{refresh:refreshSettings}=useSettings();
 const[rows,setRows]=useState([]),[text,setText]=useState(''),[source,setSource]=useState(null),[options,setOptions]=useState(()=>defaultOptions(toolId)),[result,setResult]=useState(null),[stale,setStale]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState(null),[presetName,setPresetName]=useState('');
 const{workspace,update,error:workspaceError}=useWorkspace(),cap=useCapabilities(),resultRef=useRef(null),textFile=useRef(null),running=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(!session?.user?.id)return;const incoming=takeHandoff(session.user.id,toolId);if(incoming){if(incoming.kind==='table'){setRows(incoming.rows);setOptions(defaultOptions(toolId,incoming.rows));}else setText(incoming.text||'');setSource({name:'Result from another tool',sample:false});setNotice('Previous result loaded in memory. Nothing was saved to browser storage.');}},[session?.user?.id,toolId]);
 useEffect(()=>{if(!busy)return;function warn(e){e.preventDefault();e.returnValue='';}window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[busy]);
 const connections=tool?.service==='google'?cap.data.connections.filter(c=>c.service==='google'):cap.data.credentials.filter(c=>c.service===tool?.service);
 useEffect(()=>{if(connections.length===1)setOptions(prev=>({...prev,[tool.service==='google'?'connectionId':'credentialId']:prev[tool.service==='google'?'connectionId':'credentialId']||connections[0].id}));},[JSON.stringify(connections),tool?.service]);
 if(!tool)return <ToolShell><div className="rt-content"><Notice kind="error">This tool was not found.</Notice></div></ToolShell>;
 function changeOptions(next){setOptions(next);if(result)setStale(true);}
 function onData(data,meta){setRows(data);setSource(meta);setOptions(defaultOptions(tool.id,data));setError('');setNotice('');if(result)setStale(true);}
 const connectionKey=tool.service==='google'?'connectionId':'credentialId',presets=workspace.presets.filter(p=>p.toolId===tool.id),isLocal=tool.engine==='local';
 const unavailable=tool.engine==='ai'&&!cap.loading&&!cap.data.ai.length||tool.engine==='connection'&&!cap.loading&&!connections.length;
 const connectionReady=Boolean(options[connectionKey])&&(tool.id==='sheets-reader'?Boolean(options.spreadsheetId?.trim()):Boolean(text.trim()))&&(tool.id!=='gmail-send'||Boolean(options.to?.trim()&&options.subject?.trim()))&&(tool.id!=='telegram-send'||Boolean(options.chatId?.trim()));
 const canRun=!busy&&(tool.input==='dataset'?rows.length>0:tool.engine==='connection'?connectionReady:Boolean(text.trim()))&&!unavailable&&(isLocal||!cap.loading&&!cap.error);
 async function execute(){
  if(running.current)return;running.current=true;setBusy(true);setError('');setNotice('');setDialog(null);const start=performance.now();
  try{
   let next;
   if(isLocal){await new Promise(resolve=>requestAnimationFrame(()=>setTimeout(resolve,0)));next={...runLocalTool(tool.id,{rows,text,options}),durationMs:Math.round(performance.now()-start)};}
   else{const requestId=crypto.randomUUID();const response=await request(`/api/ready-tools/${tool.id}/run`,{method:'POST',headers:{'Idempotency-Key':requestId},body:JSON.stringify({text,options,confirm:!!tool.action})});next=response.result;}
   if(!mounted.current)return;setResult(next);setStale(false);
   if(isLocal)update({action:'record-local',toolId:tool.id,rows:next.rows?.length||0,durationMs:next.durationMs}).catch(()=>setNotice('The result is ready, but activity history could not sync. You can still download your result.'));
   else refreshSettings();
   setTimeout(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),80);
  }catch(e){if(mounted.current){setError(e.message);if(!isLocal)refreshSettings();}}
  finally{running.current=false;if(mounted.current)setBusy(false);}
 }
 async function savePreset(){try{await update({action:'save-preset',toolId:tool.id,name:presetName,options});setDialog(null);setNotice('Preset saved. Input content, recipients and connection secrets are not included.');}catch(e){setError(e.message);setDialog(null);}}
 function transfer(id){if(!session?.user?.id){setError('Sign in to pass results between tools.');return;}offerHandoff(session.user.id,id,result);router.push(`/dashboard/flows/tools/${id}`);}
 const compatible=TOOLS.filter(t=>t.id!==tool.id&&(result?.kind==='table'?t.input==='dataset':t.input==='text'));
 const creditRange=cap.data.ai.length?`${Math.min(...cap.data.ai.map(p=>p.credits))}–${Math.max(...cap.data.ai.map(p=>p.credits))}`:'—';
 return <ToolShell title={tool.name}><main className="rt-content rt-runner-content"><Link className="rt-back-link" href="/dashboard/flows"><Icon name="ArrowLeft" size={16}/>Back to tool library</Link>
  <header className="rt-runner-hero"><span className={`rt-tool-icon large ${tool.engine}`}><Icon name={tool.icon} size={30}/></span><div className="rt-runner-title"><div className="rt-eyebrow">{tool.category} / READY-MADE TOOL</div><h1>{tool.name}</h1><p>{tool.description}</p></div><Button icon="Star" variant={workspace.favorites.includes(tool.id)?'selected':'ghost'} aria-pressed={workspace.favorites.includes(tool.id)} onClick={async()=>{try{await update({action:'favorite',toolId:tool.id,value:!workspace.favorites.includes(tool.id)});}catch(e){setError(e.message);}}}>{workspace.favorites.includes(tool.id)?'Saved':'Favorite'}</Button></header>
  <div className="rt-run-steps">{[['01','Add your input'],['02','Make it yours'],['03','Run & get results']].map(([number,label],i)=><div key={number} className={result&&!stale||i===0?'active':''}><span>{result&&!stale?<Icon name="Check" size={14}/>:number}</span>{label}{i<2&&<i/>}</div>)}</div>
  <div className="rt-runner-grid"><div className="rt-form-column"><section className="rt-panel"><div className="rt-panel-heading"><div><h2>{tool.input==='dataset'?'Start with your data':tool.engine==='connection'?'Choose where it goes':'What are we working on?'}</h2><p>{isLocal?'Processed in your browser. The input is not uploaded.':tool.engine==='ai'?'Your input is sent to the site’s configured AI provider.':'Only the selected account or saved connection is used.'}</p></div><span className="rt-panel-number">01</span></div><div className="rt-panel-body">
   {tool.input==='dataset'?<DatasetInput rows={rows} onData={onData} disabled={busy}/>:<>
    {tool.engine==='connection'&&<div className="rt-connection-form"><div className="rt-fields-grid"><Field label={tool.service==='google'?'Google account':'Saved connection'} value={options[connectionKey]} options={[{value:'',label:cap.loading?'Checking connections…':'Select a connection'},...connections.map(c=>({value:c.id,label:c.name}))]} disabled={busy||cap.loading} onChange={v=>changeOptions({...options,[connectionKey]:v})}/><div className="rt-connection-actions"><Link className="rt-text-link" href="/dashboard/settings?tab=connections">Manage in Settings <Icon name="ArrowUpRight" size={14}/></Link><Button icon="RefreshCw" variant="ghost" disabled={cap.loading||busy} onClick={cap.refresh}>Refresh</Button></div></div>
     {tool.id==='sheets-reader'&&<><Field label="Google Sheets link or spreadsheet ID" value={options.spreadsheetId} onChange={v=>changeOptions({...options,spreadsheetId:v})} placeholder="Paste your Google Sheets link" maxLength={300}/><div className="rt-fields-grid"><Field label="Sheet tab name" value={options.sheetName||'Sheet1'} onChange={v=>changeOptions({...options,sheetName:v})} maxLength={80}/><Field label="Maximum data rows" type="number" min={1} max={10000} value={options.rowLimit||1000} onChange={v=>changeOptions({...options,rowLimit:v})}/></div><p className="rt-fine-print">The first row is treated as column headers. Reads the first 100 columns and does not modify the sheet.</p></>}
     {tool.id==='gmail-send'&&<><Field label="Recipient email" type="email" placeholder="person@example.com" value={options.to} maxLength={254} onChange={v=>changeOptions({...options,to:v})}/><Field label="Subject" value={options.subject} maxLength={200} onChange={v=>changeOptions({...options,subject:v})}/></>}
     {tool.id==='telegram-send'&&<Field label="Chat ID or @channel_name" value={options.chatId} maxLength={100} placeholder="-1001234567890" onChange={v=>changeOptions({...options,chatId:v})} hint="Your bot must have permission to send messages to this destination."/>}
    </div>}
    {tool.id!=='sheets-reader'&&<div className="rt-text-input"><label htmlFor="rt-source-text">{tool.action?'Message':tool.id==='json-formatter'?'JSON input':'Your text or brief'}</label><textarea id="rt-source-text" rows={10} value={text} maxLength={tool.action?tool.id==='discord-send'?2000:tool.id==='telegram-send'?4096:15000:LIMITS.text} disabled={busy} onChange={e=>{setText(e.target.value);setSource(null);if(result)setStale(true);}} placeholder={tool.action?'Write the message you want to send…':tool.id==='json-formatter'?'Paste your JSON here…':'Paste your text, notes, or describe what you need…'} spellCheck={tool.id!=='json-formatter'}/><div className="rt-text-input-footer"><span>{text.length.toLocaleString()} characters</span>{!tool.action&&<><input type="file" accept=".txt,.md,.json" className="rt-sr-only" ref={textFile} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>120000)throw new Error('Text files must be smaller than 120 KB.');const value=await file.text();if(value.length>LIMITS.text)throw new Error('Use 30,000 characters or fewer.');setText(value);setSource({name:file.name});if(result)setStale(true);setError('');}catch(err){setError(err.message);}}}/><Button icon="Upload" variant="link" disabled={busy} onClick={()=>textFile.current?.click()}>Text file</Button><Button icon="Sparkles" variant="link" disabled={busy} onClick={()=>{setText(SAMPLE_TEXT[tool.id]||SAMPLE_TEXT.default);setSource({name:'Example text',sample:true});if(result)setStale(true);}}>Try example</Button></>}</div></div>}
   </>}
   {source?.sample&&<Notice icon="FlaskConical">Example data is loaded.{tool.engine==='ai'?' Running this example uses real AI credits; no fake response is substituted.':' Replace it with your own data whenever you are ready.'}</Notice>}
   {source?.note&&<p className="rt-fine-print">{source.note}</p>}
   {tool.id==='email-cleaner'&&rows.length>0&&<Field label="Column containing email addresses" value={options.emailColumn} options={[{value:'',label:'Choose email column'},...Object.keys(rows[0]).map(c=>({value:c,label:c}))]} onChange={v=>changeOptions({...options,emailColumn:v})}/>}
   {tool.id==='clean-rank'&&rows.length>0&&<div className="rt-detected"><Icon name="WandSparkles" size={17}/><p><strong>Suggested setup:</strong> duplicates by {options.duplicateColumn||'all columns'}; {options.rankColumn?`rank by ${options.rankColumn}${options.minScore!==''?`, minimum ${options.minScore}`:''}`:'no score column selected'}. Keep up to {options.limit} rows. Change these below.</p></div>}
   {tool.engine==='ai'&&tool.id==='translate'&&<Field label="Translate into" value={options.language} onChange={v=>changeOptions({...options,language:v})} options={['English','Urdu','Roman Urdu','Hindi','Arabic','Russian','Spanish','French','German','Turkish']}/>}
  </div></section>
  {tool.engine!=='connection'&&<section className="rt-panel rt-options-panel"><details open={tool.id==='column-picker'}><summary><span className="rt-options-title"><Icon name="SlidersHorizontal" size={19}/><span>Make it yours<small>Optional settings · sensible defaults included</small></span></span><Icon name="ChevronDown" size={17}/></summary><div className="rt-panel-body"><OptionsForm tool={tool} rows={rows} options={options} onChange={changeOptions}/></div></details><div className="rt-preset-bar"><label><Icon name="Bookmark" size={16}/><select aria-label="Load saved preset" value="" disabled={busy} onChange={e=>{const preset=presets.find(p=>p.id===e.target.value);if(preset){changeOptions({...defaultOptions(tool.id,rows),...preset.options});setNotice(`Loaded preset: ${preset.name}`);}}}><option value="">{presets.length?'Load a saved preset…':'No saved presets yet'}</option>{presets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Button icon="Plus" variant="link" disabled={busy} onClick={()=>{setPresetName('');setDialog('preset');}}>Save options</Button></div></section>}
  {!isLocal&&cap.error&&<Notice kind="error">{cap.error} <button className="rt-inline-button" onClick={cap.refresh}>Check again</button></Notice>}
  {unavailable&&<Notice kind="warning">{tool.engine==='ai'?'AI is not configured on this website yet. The site owner must add a working provider API key. Visitors do not need to bring their own key.':<>No matching account is connected. Open <Link href="/dashboard/settings?tab=connections">Settings → Connections</Link>, connect it once, then return and press Refresh.</>}</Notice>}
  {error&&<Notice kind="error">{error}</Notice>}{notice&&<Notice kind="success">{notice}</Notice>}
  <div className="rt-run-action"><div><strong>{busy?(isLocal?'Processing your input…':'Waiting for the connected service…'):tool.action?'You are in control.':'Let’s get this done.'}</strong><small>{busy?'Keep this page open until the result appears.':isLocal?'No external account or AI credits required.':tool.engine==='ai'?`${creditRange} credits per successful run, depending on the selected provider.`:tool.action?'An explicit confirmation is required before sending a message.':'Read-only: your connected spreadsheet will not be modified.'}</small></div><Button icon={busy?'Loader2':tool.action?'Send':'Play'} className={busy?'rt-working':''} variant="primary large" disabled={!canRun} onClick={()=>tool.action?setDialog('confirm'):execute()}>{busy?'Working…':tool.action?'Review & send':result?'Run again':'Run tool'}<Icon name="ArrowRight" size={16}/></Button></div>
  </div><aside className="rt-runner-aside"><section className="rt-info-card"><div className="rt-eyebrow">YOUR SHORTCUT, EXPLAINED</div><h3>From input to done.</h3><ol>{tool.steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,'0')}</span><div>{step}</div></li>)}</ol></section><section className="rt-info-card subtle"><Icon name={isLocal?'ShieldCheck':tool.action?'ShieldAlert':'Sparkles'} size={22}/><h3>{isLocal?'Your original stays yours.':tool.action?'Review. Confirm. Send.':'Real AI, not a demo.'}</h3><p>{isLocal?'Files stay in this browser while you work. Activity history stores counts and tool names, not your data.':tool.action?'We do not send anything when you open this tool. Review the destination and complete message before confirming.':'The site’s configured AI provider processes your input. Results may contain mistakes, so review them before use.'}</p>{tool.note&&<p>{tool.note}</p>}</section><div className="rt-aside-links"><Link href="/dashboard/settings?tab=tools"><Icon name="Settings2" size={15}/>Tool preferences <Icon name="ArrowUpRight" size={14}/></Link><Link href="/dashboard/settings?tab=connections"><Icon name="Plug" size={15}/>Manage connections <Icon name="ArrowUpRight" size={14}/></Link><Link href="/dashboard/flows/workflows"><Icon name="Workflow" size={15}/>Advanced workflows <Icon name="ArrowUpRight" size={14}/></Link></div></aside></div>
  <div ref={resultRef} className="rt-result-anchor">{result&&<ResultView result={result} tool={tool} stale={stale} defaultExport={workspace.preferences?.defaultExport||'csv'} onTransfer={transfer} compatible={compatible}/>}</div>
  <footer className="rt-page-footer"><span>Theme and connections are managed in Settings.</span><span>Files and outputs are not saved to activity history.</span></footer>
 </main>
 {dialog==='preset'&&<Dialog title="Save these tool options" onClose={()=>setDialog(null)} footer={<><Button onClick={()=>setDialog(null)}>Cancel</Button><Button icon="Bookmark" variant="primary" disabled={!presetName.trim()} onClick={savePreset}>Save preset</Button></>}><Field label="Preset name" value={presetName} onChange={setPresetName} maxLength={60} placeholder="My weekly cleanup" autoFocus/><p className="rt-fine-print">Saves selected options, column names and filter values. Input content, connection IDs and message recipients are excluded. Do not put secrets in filter values.</p>{workspaceError&&<Notice kind="error">{workspaceError}</Notice>}</Dialog>}
 {dialog==='confirm'&&<Dialog title="Confirm this external action" onClose={()=>setDialog(null)} footer={<><Button onClick={()=>setDialog(null)}>Go back</Button><Button icon="Send" variant="primary" onClick={execute}>Confirm & send once</Button></>}><Notice kind="warning">This sends a real message. Check the destination and content. A network failure can leave delivery uncertain; never retry blindly.</Notice><dl className="rt-confirm-details"><dt>Tool</dt><dd>{tool.name}</dd><dt>Connection</dt><dd>{connections.find(c=>c.id===options[connectionKey])?.name||'Selected connection'}</dd>{(options.to||options.chatId)&&<><dt>Destination</dt><dd>{options.to||options.chatId}</dd></>}{options.subject&&<><dt>Subject</dt><dd>{options.subject}</dd></>}</dl><h3>Complete message</h3><pre className="rt-confirm-message">{text}</pre></Dialog>}
 </ToolShell>;
}
