import test from 'node:test';
import assert from 'node:assert/strict';
import { NODE_TYPES } from '../../components/flows/nodeTypesConfig.js';
import { TOOLS,defaultOptions,SAMPLE_ROWS } from '../../lib/readyTools/catalog.mjs';
import { PRO_TEMPLATES,buildProTemplate } from '../../lib/flowPro/templates.mjs';
import { normalizeGraph } from '../../lib/flowPro/graph.mjs';
import { EXTRA_NODES,CREDIT_PREFIX,checkedCost,priceSteps,readyRecipe,flowQuote,DEFAULT_POLICY,receiptFromHold } from '../../lib/automationCredits/pricing.mjs';
const costs=Object.fromEntries([...NODE_TYPES,...EXTRA_NODES].map(n=>[CREDIT_PREFIX+n.type,{cost:1}]));
test('defaults: one per node, tests free, billing enabled',()=>{assert.equal(DEFAULT_POLICY.enabled,true);assert.equal(DEFAULT_POLICY.chargeTests,false);assert.equal(priceSteps([{nodeId:'a',type:'ai.prompt'}],costs).total,1);});
for(const value of [-1,0.5,NaN,Infinity,-Infinity,10001,'1',null,undefined])test(`invalid administrator cost is rejected: ${String(value)}`,()=>assert.throws(()=>checkedCost(value)));
for(const value of [0,1,500,10000])test(`valid administrator cost: ${value}`,()=>assert.equal(checkedCost(value),value));
for(const tool of TOOLS)test(`ready tool ${tool.id} has a complete priced recipe`,()=>{const q=priceSteps(readyRecipe(tool.id,defaultOptions(tool.id,SAMPLE_ROWS)),costs);assert(q.lines.length>0);assert.equal(q.total,q.lines.length);assert.equal(new Set(q.lines.map(l=>l.nodeId)).size,q.lines.length);});
test('clean-rank default sample costs five, independent of record count',()=>{const q=priceSteps(readyRecipe('clean-rank',defaultOptions('clean-rank',SAMPLE_ROWS)),costs);assert.equal(q.total,5);assert.deepEqual(q.lines.map(l=>l.type),['ready.cleanRows','data.deduplicate','data.filter','data.sort','data.limit']);});
test('optional filters and ranking are not priced when not selected',()=>{const q=priceSteps(readyRecipe('clean-rank',{trim:false,rankColumn:'',minScore:''}),costs);assert.equal(q.total,2);});
test('administrator override is used by both tools and flow nodes',()=>{const custom={...costs,[CREDIT_PREFIX+'data.deduplicate']:{cost:7}};const q=priceSteps(readyRecipe('remove-duplicates',{trim:false}),custom);assert.equal(q.total,7);});
test('zero-cost override is honored',()=>assert.equal(priceSteps([{nodeId:'n',type:'ai.prompt'}],{...costs,[CREDIT_PREFIX+'ai.prompt']:{cost:0}}).total,0));
test('missing configuration fails closed, not free',()=>assert.throws(()=>priceSteps([{nodeId:'n',type:'unknown'}],costs)));
test('disabled billing produces zero-priced runs',()=>assert.equal(priceSteps(readyRecipe('blueprint'),costs,{...DEFAULT_POLICY,enabled:false}).total,0));
test('admin run cap marks over-limit quote',()=>assert.equal(priceSteps(readyRecipe('blueprint'),costs,{...DEFAULT_POLICY,maxRunCredits:0}).overLimit,true));
const n=(id,type='logic.noop',data={})=>({nodeId:id,type,data}),e=(a,b)=>({edgeId:a+'-'+b,source:a,target:b});
const graph={nodes:[n('start','trigger.manual'),n('a'),n('b'),n('orphan'),n('note','utility.note')],edges:[e('start','a'),e('a','b')]};
test('quote excludes notes and disconnected nodes',()=>assert.equal(flowQuote(graph,costs).total,3));
test('selected-node execution only reserves ancestors',()=>assert.equal(flowQuote(graph,costs,DEFAULT_POLICY,{untilNodeId:'a'}).total,2));
test('invalid selected node is rejected',()=>assert.throws(()=>flowQuote(graph,costs,DEFAULT_POLICY,{untilNodeId:'missing'})));
test('disabled nodes pass through but do not charge',()=>{const g=structuredClone(graph);g.nodes[1].data.disabled=true;assert.equal(flowQuote(g,costs).total,2);});
test('test mode is free by default',()=>assert.equal(flowQuote(graph,costs,DEFAULT_POLICY,{mode:'test'}).total,0));
test('paid-test policy only charges unpinned native steps',()=>{const g={nodes:[n('s','trigger.manual'),n('x','ai.prompt'),n('p','logic.noop',{pinned:true}),n('z')],edges:[e('s','x'),e('x','p'),e('p','z')]};assert.equal(flowQuote(g,costs,{...DEFAULT_POLICY,chargeTests:true},{mode:'test'}).total,2);});
test('seeded trigger selection excludes other isolated triggers',()=>{const g={nodes:[n('s','trigger.manual'),n('t','trigger.webhook'),n('x')],edges:[e('s','x')]};assert.equal(flowQuote(g,costs,DEFAULT_POLICY,{seedIds:['t']}).total,1);});
test('receipt refunds only unused or confirmed failed amounts',()=>{const r=receiptFromHold({key:'x',reserved:10,units:[{cost:2,status:'success'},{cost:3,status:'failed'},{cost:1,status:'started'}]});assert.equal(r.charged,3);assert.equal(r.refunded,7);assert(r.uncertain);});
test('credits from an old plan cycle are not minted in a new cycle',()=>{const r=receiptFromHold({reserved:10,units:[]},{sameCycle:false});assert.equal(r.refunded,0);assert.equal(r.expiredUnused,10);});
test('receipt accounting cannot exceed the reservation',()=>assert.throws(()=>receiptFromHold({reserved:1,units:[{cost:2,status:'success'}]})));
for(const t of PRO_TEMPLATES)test(`workflow template ${t.id} can be quoted`,()=>{const q=flowQuote(normalizeGraph(buildProTemplate(t)),costs);assert(Number.isInteger(q.total));assert(q.total>=0);});
