'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import './studio.css';
import { Icon,Button,Brand,Empty,Modal,api,dateLabel,NodeIcon } from './UI';
import { TemplateModal,CredentialModal,AIBuilderModal } from './Panels';
import { getNodeTypeDef,NODE_TYPES } from '../nodeTypesConfig';
import { importWorkflow } from '../../../lib/flowPro/graph.mjs';
export default function FlowHub(){
 const router=useRouter(),fileInput=useRef(null);const[flows,setFlows]=useState(null),[stats,setStats]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(null),[confirm,setConfirm]=useState(null),[toast,setToast]=useState(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('updated'),[theme,setTheme]=useState('dark'),[name,setName]=useState(''),[description,setDescription]=useState('');
 function notify(message,isError=false){setToast({message,error:isError});}
 async function refresh(){try{const data=await api('/api/flows');setFlows(data.flows||[]);setStats(data.stats||{});setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{try{setTheme(JSON.parse(localStorage.getItem('mm-studio-theme'))||'dark');}catch{}refresh();},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),5500);return()=>clearTimeout(t);}},[toast]);
 async function create(payload){if(busy)return;setBusy(true);try{const data=await api('/api/flows',{method:'POST',body:JSON.stringify(payload)});router.push(`/dashboard/flows/${data.flow._id}`);}catch(e){notify(e.message,true);setBusy(false);}}
 async function duplicate(flow){try{const data=await api(`/api/flows/${flow._id}`);await create({...data.flow,name:`${data.flow.name} (copy)`.slice(0,80)});}catch(e){notify(e.message,true);}}
 async function star(flow){try{await api(`/api/flows/${flow._id}`,{method:'PUT',body:JSON.stringify({starred:!flow.starred,revision:flow.revision})});refresh();}catch(e){notify(e.message,true);}}
 const list=(flows||[]).filter(f=>(filter==='all'||filter==='starred'&&f.starred||filter===f.status)&&`${f.name} ${f.description} ${f.tags?.join(' ')} ${f.folder}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):new Date(b.updatedAt)-new Date(a.updatedAt));
 const active=(flows||[]).filter(f=>f.status==='active').length;
 return <div className="fp fp-hub" data-studio-theme={theme}><aside className="fp-nav"><Brand/><div className="fp-workspace-card"><div className="fp-avatar">MW</div><div className="fp-grow"><strong style={{fontSize:11}}>My workspace</strong><p className="fp-muted" style={{fontSize:9}}>Personal automations</p></div><Icon name="ChevronsUpDown" size={11}/></div><div className="fp-nav-section">Workspace</div>{[['all','Workflow','All workflows'],['active','Zap','Active workflows'],['draft','FilePenLine','Drafts'],['starred','Star','Starred']].map(([key,icon,label])=><button key={key} className={`fp-nav-link ${filter===key?'active':''}`} onClick={()=>setFilter(key)}><Icon name={icon} size={16}/><span>{label}</span><small>{key==='all'?flows?.length||0:key==='active'?active:key==='draft'?flows?.filter(f=>f.status==='draft').length||0:flows?.filter(f=>f.starred).length||0}</small></button>)}<div className="fp-nav-section">Build & connect</div><button className="fp-nav-link" onClick={()=>setModal('templates')}><Icon name="LayoutTemplate"/><span>Template library</span></button><button className="fp-nav-link" onClick={()=>setModal('ai')}><Icon name="Sparkles"/><span>AI workflow builder</span></button><button className="fp-nav-link" onClick={()=>setModal('credentials')}><Icon name="KeyRound"/><span>Credentials</span></button><Link className="fp-nav-link" href="/flow-studio"><Icon name="FlaskConical"/><span>Local sandbox</span></Link><div className="fp-nav-bottom"><div className="fp-nav-section">MultiMind</div><Link className="fp-nav-link" href="/dashboard"><Icon name="ArrowLeft"/><span>Back to dashboard</span></Link><Link className="fp-nav-link" href="/dashboard/settings"><Icon name="Settings2"/><span>Account settings</span></Link><p className="fp-muted" style={{fontSize:9,padding:'15px 13px 0'}}>FLOW STUDIO / VERSION 2.0</p></div></aside>
 <main className="fp-hub-main"><header className="fp-hub-top"><Icon name="House" size={13}/><span className="fp-muted">Workspace</span><Icon name="ChevronRight" size={11}/><span>Flows</span><div className="fp-spacer"/><span className="fp-chip purple fp-hide-small">Automation workspace</span><Button icon={theme==='dark'?'Sun':'Moon'} title="Toggle studio theme" variant="ghost" onClick={()=>{const next=theme==='dark'?'light':'dark';setTheme(next);localStorage.setItem('mm-studio-theme',JSON.stringify(next));}}/><div className="fp-avatar">ME</div></header><div className="fp-hub-content"><div className="fp-hero"><div><div className="fp-overline">Less busywork. More possibility.</div><h1>Your work, on autopilot.</h1><p>Connect your tools, put AI to work, and turn everyday processes into thoughtful automations. One canvas. Your rules.</p></div><div className="fp-row"><Button icon="Upload" onClick={()=>fileInput.current?.click()}>Import</Button><Button icon="Plus" variant="primary" disabled={busy} onClick={()=>{setName('');setDescription('');setModal('create');}}>New workflow</Button></div></div>
 <div className="fp-metrics">{[['Total workflows',flows?.length??'—','Your automation library','Workflow'],['Active workflows',flows?active:'—','Ready for configured triggers','Zap'],['Recent executions',flows?stats.runs??0:'—','Last 30 days · up to 2,000 runs','Activity'],['Success rate',stats.successRate==null?'—':`${stats.successRate}%`,'Measured from recent executions','CircleCheck']].map(([label,value,note,icon])=><div className="fp-metric" key={label}><div className="fp-metric-label"><span>{label}</span><Icon name={icon} size={14}/></div><div className="fp-metric-value">{value}</div><div className="fp-metric-note">{note}</div></div>)}</div>
 <div className="fp-feature-banner"><div className="fp-feature-art"><span className="fp-art-node"><Icon name="Webhook" size={14}/></span><span className="fp-art-node"><Icon name="Brain" size={14}/></span><span className="fp-art-node"><Icon name="Send" size={14}/></span><span className="fp-art-line"/></div><div className="fp-grow"><div className="fp-overline" style={{marginBottom:5,fontSize:8}}>START WITH A HEAD START</div><h3>A great workflow starts with a good pattern.</h3><p>Lead routing, data cleanup, AI content, support triage and more. Make a template your own.</p></div><Button icon="ArrowUpRight" onClick={()=>setModal('templates')}>Explore templates</Button></div>
 <div className="fp-row fp-between" style={{marginBottom:17}}><h3>{filter==='starred'?'Starred workflows':filter==='active'?'Active workflows':filter==='draft'?'Draft workflows':'Your workflows'} <span className="fp-muted" style={{fontSize:11,fontWeight:400}}> / {list.length}</span></h3><Link href="/flow-studio" className="fp-btn ghost small">Try the sandbox <Icon name="ArrowUpRight" size={12}/></Link></div><div className="fp-library-toolbar"><div className="fp-search"><Icon name="Search" size={14}/><input aria-label="Search workflows" placeholder="Search workflows, tags or folders…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter workflow status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All workflows</option><option value="active">Active</option><option value="draft">Draft</option><option value="paused">Paused</option><option value="starred">Starred</option></select><div className="fp-spacer"/><select aria-label="Sort workflows" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">Last edited</option><option value="name">Name A–Z</option></select><Button icon="RefreshCw" variant="ghost" title="Refresh workflows" onClick={refresh}/></div>
 {error&&<div className="fp-banner error" style={{marginBottom:20,borderRadius:8}}><Icon name="CircleAlert"/><span className="fp-grow">{error}</span><Button variant="small" onClick={refresh}>Retry</Button></div>}
 {!flows&&!error?<Empty icon="Workflow" title="Opening your workspace" description="Loading workflow data…"/>:<div className="fp-grid">{list.map(f=><article className="fp-flow-card" key={f._id}><Link href={`/dashboard/flows/${f._id}`}><div className="fp-mini-graph">{(f.nodeTypes?.length?f.nodeTypes:['trigger.manual','logic.condition','utility.log']).slice(0,5).map((type,i)=><span key={`${type}-${i}`} style={{display:'contents'}}>{i>0&&<span className="fp-mini-wire"/>}<span className="fp-mini-node"><Icon name={getNodeTypeDef(type)?.icon||'Workflow'} size={15}/></span></span>)}{!f.nodeCount&&<span className="fp-muted" style={{fontSize:9,marginLeft:10}}>Start building</span>}</div><div className="fp-flow-card-body"><div className="fp-row fp-between"><span className={`fp-chip ${f.status==='active'?'green':f.status==='paused'?'orange':''}`}><span className="fp-dot"/>{f.status}</span><span className="fp-muted" style={{fontSize:9}}>{f.nodeCount} steps</span></div><h3>{f.name}</h3><p>{f.description||'An open canvas for your next great automation.'}</p><div className="fp-flow-card-tags">{(f.tags?.length?f.tags:[f.folder||'Personal']).slice(0,3).map(t=><span key={t} className="fp-chip">{t}</span>)}</div></div></Link><div className="fp-card-bottom"><span>Edited {dateLabel(f.updatedAt)}</span><div className="fp-card-actions"><Button icon="Star" variant={f.starred?'active small':'ghost small'} title={f.starred?'Unstar workflow':'Star workflow'} onClick={()=>star(f)}/><Button icon="Copy" variant="ghost small" title="Duplicate workflow" disabled={busy} onClick={()=>duplicate(f)}/><Button icon="Trash2" variant="ghost small" title="Delete workflow" onClick={()=>setConfirm(f)}/></div></div></article>)}<button className="fp-create-card" onClick={()=>{setName('');setDescription('');setModal('create');}}><span className="fp-empty-icon" style={{width:40,height:40,borderRadius:12}}><Icon name="Plus" size={20}/></span><h3>Build your next workflow</h3><p>Start with a blank canvas or use a ready-to-edit template.</p></button></div>}
 </div></main>
 <input ref={fileInput} type="file" accept=".json,application/json" style={{display:'none'}} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const value=importWorkflow(await file.text(),NODE_TYPES);await create(value);}catch(err){notify(err.message,true);}}}/>
 {modal==='templates'&&<TemplateModal onClose={()=>setModal(null)} onPick={t=>create({templateId:t.id})}/>}
 {modal==='create'&&<Modal title="Create a workflow" subtitle="Every great automation starts with a clear outcome." onClose={()=>setModal(null)} footer={<><Button onClick={()=>setModal('templates')} icon="LayoutTemplate">Use a template</Button><Button variant="primary" icon="Plus" disabled={busy||!name.trim()} onClick={()=>create({name,description})}>{busy?'Creating…':'Create workflow'}</Button></>}><div className="fp-field"><label>Workflow name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Customer onboarding" maxLength={80} aria-label="New workflow name"/></div><div className="fp-field"><label>Description</label><textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} placeholder="What will this workflow do?" aria-label="New workflow description"/></div></Modal>}
 {modal==='credentials'&&<CredentialModal onClose={()=>setModal(null)} notify={notify}/>}
 {modal==='ai'&&<AIBuilderModal onClose={()=>setModal(null)} notify={notify} onApply={draft=>create(draft)}/>}
 {confirm&&<Modal title={`Delete “${confirm.name}”?`} subtitle="This action cannot be undone." onClose={()=>setConfirm(null)} footer={<><Button onClick={()=>setConfirm(null)}>Keep workflow</Button><Button variant="danger" icon="Trash2" disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/api/flows/${confirm._id}`,{method:'DELETE'});setConfirm(null);await refresh();notify('Workflow deleted');}catch(e){notify(e.message,true);}finally{setBusy(false);}}}>Delete permanently</Button></>}><p className="fp-muted">The workflow, all execution history, and all saved versions will be permanently deleted.</p></Modal>}
 {toast&&<div className={`fp-toast ${toast.error?'error':''}`} role="status"><Icon name={toast.error?'CircleAlert':'CircleCheck'}/>{toast.message}<Button icon="X" variant="ghost small" title="Dismiss notification" onClick={()=>setToast(null)}/></div>}
 </div>;
}
