'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import {useSettings} from '@/lib/SettingsContext';
import ReactFlow,{ReactFlowProvider,Background,MiniMap,addEdge,useNodesState,useEdgesState,SelectionMode,updateEdge} from 'reactflow';
import 'reactflow/dist/style.css';
import './studio.css';
import ProNode,{StickyNote,ProEdge} from './ProNode';
import Palette from './Palette';
import Inspector from './Inspector';
import { RunPanel,ExecutionsPanel,VersionsPanel,SettingsPanel,TemplateModal,CommandModal,CredentialModal,AIBuilderModal } from './Panels';
import { Icon,Button,Brand,Modal,Empty,api,downloadJSON,downloadText,dateLabel,JsonView } from './UI';
import { NODE_TYPES,getNodeTypeDef } from '../nodeTypesConfig';
import { buildFlowFromTemplate } from '../../../lib/flowTemplates';
import { PRO_TEMPLATES,buildProTemplate } from '../../../lib/flowPro/templates.mjs';
import { normalizeGraph,toCanvas,uid,autoLayout,validateGraph,wouldCycle,exportWorkflow,importWorkflow } from '../../../lib/flowPro/graph.mjs';
import { executeWorkflow } from '../../../lib/flowPro/engine.mjs';
import { parseJSON } from '../../../lib/flowPro/expressions.mjs';
const nodeTypes={proNode:ProNode,stickyNote:StickyNote},edgeTypes={proEdge:ProEdge};
const DEMO_KEY='multimind-flow-studio-demo-v2';
function initialDemo(){return {_id:'demo',revision:1,status:'draft',folder:'Personal',starred:false,settings:{concurrency:3,timeoutMs:90000},...buildProTemplate(PRO_TEMPLATES[0])};}
function safeStorage(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
function GraphEditor({flowId,demo=false}){
 const {settings:globalSettings}=useSettings();const theme=['light','sepia'].includes(globalSettings.theme)?'light':'dark';
 async function goToSettings(tab){try{if(flow)await saveCurrent();window.location.assign(`/dashboard/settings?tab=${tab}`);}catch(e){notify(e.message,true);}}
 const [flow,setFlow]=useState(null),[loadError,setLoadError]=useState('');
 const [nodes,setNodes,baseNodesChange]=useNodesState([]),[edges,setEdges,baseEdgesChange]=useEdgesState([]);
 const [instance,setInstance]=useState(null),[selectedId,setSelectedId]=useState(null),[edgeEdit,setEdgeEdit]=useState(null);
 const [tab,setTab]=useState('editor'),[showLibrary,setShowLibrary]=useState(true),[showMinimap,setShowMinimap]=useState(true),[snap,setSnap]=useState(true),[zoom,setZoom]=useState(100);
 const [modal,setModal]=useState(null),[confirm,setConfirm]=useState(null),[toast,setToast]=useState(null),[saveState,setSaveState]=useState('saved'),[saveError,setSaveError]=useState('');
 const [run,setRun]=useState(null),[running,setRunning]=useState(false),[showConsole,setShowConsole]=useState(false),[runs,setRuns]=useState([]),[mode,setMode]=useState('test');
 const [versions,setVersions]=useState([]),[checkpointName,setCheckpointName]=useState(''),[inputText,setInputText]=useState('{}'),[inputError,setInputError]=useState(''),[webhook,setWebhook]=useState(null);
 const [historyCount,setHistoryCount]=useState({past:0,future:0});
 const wrapper=useRef(null),fileInput=useRef(null),loaded=useRef(false),latest=useRef(null),savedSignature=useRef(''),revision=useRef(1),saving=useRef(null),timer=useRef(null),toastTimer=useRef(null),history=useRef({past:[],future:[]}),clipboard=useRef(null),abort=useRef(null),livePoll=useRef(null),mounted=useRef(true);
 const graph=useMemo(()=>normalizeGraph({nodes,edges}),[nodes,edges]);
 const snapshot=useMemo(()=>flow?{name:flow.name,description:flow.description||'',status:flow.status,tags:flow.tags||[],folder:flow.folder||'Personal',starred:!!flow.starred,variables:flow.variables||{},testInput:flow.testInput||{},settings:flow.settings||{},...graph}:null,[flow,graph]);
 latest.current=snapshot;
 const signature=JSON.stringify(snapshot);
 const issues=useMemo(()=>validateGraph(graph,NODE_TYPES,{forRun:true,mode}),[graph,mode]);
 const selected=nodes.find(n=>n.id===selectedId)||null;
 const notify=useCallback((message,error=false)=>{clearTimeout(toastTimer.current);setToast({message,error});toastTimer.current=setTimeout(()=>setToast(null),6500);},[]);
 function refreshHistory(){setHistoryCount({past:history.current.past.length,future:history.current.future.length});}
 function remember(){const value=normalizeGraph({nodes,edges});const past=history.current.past;if(JSON.stringify(past.at(-1))!==JSON.stringify(value)){past.push(value);if(past.length>50)past.shift();}history.current.future=[];refreshHistory();}
 function applyGraph(value,record=true){if(record)remember();const next=toCanvas(normalizeGraph(value));setNodes(next.nodes);setEdges(next.edges);setSelectedId(null);}
 function updateFlow(patch){setFlow(f=>({...f,...patch}));}
 useEffect(()=>{mounted.current=true;if(window.innerWidth<1000)setShowLibrary(false);let cancelled=false;async function load(){try{const data=demo?safeStorage(DEMO_KEY,initialDemo()):(await api(`/api/flows/${flowId}`)).flow;if(cancelled)return;const converted=toCanvas(normalizeGraph(data));revision.current=data.revision||1;setFlow(data);setNodes(converted.nodes);setEdges(converted.edges);setInputText(JSON.stringify(data.testInput||{},null,2));if(demo){setRuns(safeStorage(`${DEMO_KEY}-runs`,[]));setVersions(safeStorage(`${DEMO_KEY}-versions`,[]));}loaded.current=false;requestAnimationFrame(()=>{loaded.current=true;});}catch(e){if(!cancelled)setLoadError(e.message);}}load();return()=>{cancelled=true;mounted.current=false;clearTimeout(timer.current);clearTimeout(toastTimer.current);clearInterval(livePoll.current);abort.current?.abort();};},[flowId,demo]);
 useEffect(()=>{if(!snapshot)return;if(savedSignature.current==='')savedSignature.current=signature;if(!loaded.current||signature===savedSignature.current)return;setSaveState('unsaved');clearTimeout(timer.current);timer.current=setTimeout(()=>{saveCurrent().catch(()=>{});},1100);return()=>clearTimeout(timer.current);},[signature]);
 useEffect(()=>{if(instance&&flow){const id=setTimeout(()=>instance.fitView({padding:.18,maxZoom:.9,duration:250}),120);return()=>clearTimeout(id);}},[instance,!!flow]);
 useEffect(()=>{function warn(e){if(latest.current&&JSON.stringify(latest.current)!==savedSignature.current){e.preventDefault();e.returnValue='';}}window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 async function saveCurrent(){
  clearTimeout(timer.current);
  if(saving.current){await saving.current;return saveCurrent();}
  const payload=latest.current;if(!payload)return false;const encoded=JSON.stringify(payload);if(encoded===savedSignature.current){setSaveState('saved');return true;}
  const structural=validateGraph(payload,NODE_TYPES).filter(i=>i.severity==='error');if(structural.length){setSaveError(structural[0].message);setSaveState('error');throw new Error(structural[0].message);}
  setSaveState('saving');
  const promise=(async()=>{try{if(demo){localStorage.setItem(DEMO_KEY,JSON.stringify({...payload,_id:'demo',revision:++revision.current}));}else{const data=await api(`/api/flows/${flowId}`,{method:'PUT',body:JSON.stringify({...payload,revision:revision.current})});revision.current=data.flow.revision;}savedSignature.current=encoded;setSaveState('saved');setSaveError('');return true;}catch(e){setSaveState('error');setSaveError(e.message);throw e;}})();
  saving.current=promise;try{return await promise;}finally{saving.current=null;}
 }
 function commitNodes(nextNodes,nextEdges=edges){remember();setNodes(nextNodes);setEdges(nextEdges);}
 function addNode(type,position){const def=getNodeTypeDef(type);if(!def)return;if(nodes.length>=200){notify('A workflow supports up to 200 nodes',true);return;}
  const bounds=wrapper.current?.getBoundingClientRect();const pos=position||((instance&&bounds)?instance.project({x:bounds.width*.4,y:bounds.height*.4}):{x:100+nodes.length*40,y:160});
  const config=Object.fromEntries((def.configSchema||[]).filter(f=>f.default!==undefined).map(f=>[f.key,f.default]));const node={id:uid(),type:type==='utility.note'?'stickyNote':'proNode',position:pos,data:{nodeType:type,label:def.label,config}};
  commitNodes([...nodes,node]);setSelectedId(node.id);setTab('editor');if(window.innerWidth<1000)setShowLibrary(false);
 }
 function changeNode(id,patch){remember();setNodes(list=>list.map(n=>n.id===id?{...n,data:{...n.data,...patch}}:n));}
 function deleteNodes(ids){const set=new Set(ids);commitNodes(nodes.filter(n=>!set.has(n.id)),edges.filter(e=>!set.has(e.source)&&!set.has(e.target)));setSelectedId(null);}
 function duplicate(ids,offset=48){const idsSet=new Set(ids),subset=nodes.filter(n=>idsSet.has(n.id));if(!subset.length)return;if(nodes.length+subset.length>200){notify('Too many nodes',true);return;}const mapping=new Map(subset.map(n=>[n.id,uid()]));const copies=subset.map(n=>{const data=JSON.parse(JSON.stringify(n.data));for(const[oldId,newId]of mapping){if(data.config)data.config=JSON.parse(JSON.stringify(data.config).replaceAll(`$node.${oldId}`,`$node.${newId}`));}return {...n,id:mapping.get(n.id),position:{x:n.position.x+offset,y:n.position.y+offset},selected:true,data};});const copiedEdges=edges.filter(e=>mapping.has(e.source)&&mapping.has(e.target)).map(e=>({...e,id:uid('edge'),source:mapping.get(e.source),target:mapping.get(e.target)}));commitNodes([...nodes.map(n=>({...n,selected:false})),...copies],[...edges,...copiedEdges]);setSelectedId(copies[0]?.id);}
 function copySelection(){const ids=new Set(nodes.filter(n=>n.selected||n.id===selectedId).map(n=>n.id));clipboard.current=normalizeGraph({nodes:nodes.filter(n=>ids.has(n.id)),edges:edges.filter(e=>ids.has(e.source)&&ids.has(e.target))});notify(`${ids.size} node(s) copied`);}
 function pasteSelection(){const value=clipboard.current;if(!value?.nodes?.length)return;if(nodes.length+value.nodes.length>200){notify('Too many nodes',true);return;}const map=new Map(value.nodes.map(n=>[n.nodeId,uid()]));const pasted=toCanvas({nodes:value.nodes.map(n=>({...n,nodeId:map.get(n.nodeId),position:{x:n.position.x+60,y:n.position.y+60},data:JSON.parse(JSON.stringify(n.data).replace(/\$node\.([\w-]+)/g,(m,id)=>map.has(id)?`$node.${map.get(id)}`:m))})),edges:value.edges.map(e=>({...e,edgeId:uid('edge'),source:map.get(e.source),target:map.get(e.target)}))});commitNodes([...nodes,...pasted.nodes],[...edges,...pasted.edges]);notify('Nodes pasted');}
 function undo(){if(!history.current.past.length)return;history.current.future.push(normalizeGraph({nodes,edges}));const previous=history.current.past.pop();applyGraph(previous,false);refreshHistory();}
 function redo(){if(!history.current.future.length)return;history.current.past.push(normalizeGraph({nodes,edges}));applyGraph(history.current.future.pop(),false);refreshHistory();}
 function layout(direction='LR'){try{applyGraph(autoLayout(graph,direction));setTimeout(()=>instance?.fitView({padding:.2,duration:300}),80);}catch(e){notify(e.message,true);}}
 function isValidConnection(c){return c.source!==c.target&&!nodes.find(n=>n.id===c.target)?.data?.nodeType?.startsWith('trigger.')&&!wouldCycle(c.source,c.target,edges);}
 function connect(c){if(!isValidConnection(c)){notify('This connection would create a cycle or connect into a trigger',true);return;}remember();setEdges(es=>addEdge({...c,type:'proEdge'},es));}
 function focusNode(id){setSelectedId(id);setTab('editor');instance?.fitView({nodes:[{id}],padding:.5,maxZoom:1,duration:300});}
 function exportJSON(){downloadJSON(exportWorkflow({...flow,...graph}),`${(flow.name||'workflow').replace(/[^a-z0-9-]/gi,'-')}.json`);notify('Workflow exported. Saved credential references and pinned data were removed.');}
 function exportSVG(){const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));if(!nodes.length)return;const minX=Math.min(...nodes.map(n=>n.position.x))-60,minY=Math.min(...nodes.map(n=>n.position.y))-60,maxX=Math.max(...nodes.map(n=>n.position.x))+330,maxY=Math.max(...nodes.map(n=>n.position.y))+230;const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${minX} ${minY} ${maxX-minX} ${maxY-minY}"><rect x="${minX}" y="${minY}" width="${maxX-minX}" height="${maxY-minY}" fill="#0c0e14"/>${edges.map(e=>{const a=nodes.find(n=>n.id===e.source),b=nodes.find(n=>n.id===e.target);if(!a||!b)return '';const x1=a.position.x+244,y1=a.position.y+60,x2=b.position.x,y2=b.position.y+60;return `<path d="M ${x1} ${y1} C ${x1+60} ${y1},${x2-60} ${y2},${x2} ${y2}" fill="none" stroke="#7c819c" stroke-width="2"/>`;}).join('')}${nodes.map(n=>`<g><rect x="${n.position.x}" y="${n.position.y}" width="244" height="120" rx="12" fill="#161a24" stroke="#625787"/><text x="${n.position.x+18}" y="${n.position.y+43}" fill="#ebe8f8" font-family="Arial,sans-serif" font-size="14">${escape((n.data.label||getNodeTypeDef(n.data.nodeType)?.label||n.data.nodeType).slice(0,28))}</text><text x="${n.position.x+18}" y="${n.position.y+72}" fill="#a3a5bc" font-family="Arial,sans-serif" font-size="10">${escape(n.data.nodeType)}</text></g>`).join('')}</svg>`;downloadText(svg,'workflow-diagram.svg','image/svg+xml');}
 function replaceFlow(value){applyGraph(value);updateFlow({name:value.name||flow.name,description:value.description||'',variables:value.variables||{},testInput:value.testInput||{},tags:value.tags||[],status:'draft'});setInputText(JSON.stringify(value.testInput||{},null,2));setModal(null);setConfirm(null);setRun(null);setTab('editor');setTimeout(()=>instance?.fitView({padding:.2,duration:300}),100);notify('Draft loaded. Review the graph before running.');}
 function chooseTemplate(template){const value={...buildFlowFromTemplate(template),name:template.flowName,description:template.flowDescription,variables:template.variables||{},testInput:template.testInput||{},tags:template.tags||[]};if(nodes.length){setModal(null);setConfirm({title:'Replace the current graph?',message:'This loads the selected template as a draft. Your current graph remains available through Undo; save a checkpoint for a persistent backup.',action:()=>replaceFlow(value)});}else replaceFlow(value);}
 async function refreshRuns(){if(demo)return;try{const data=await api(`/api/flows/${flowId}/runs`);setRuns(data.runs||[]);}catch(e){notify(e.message,true);}}
 async function refreshVersions(){if(demo)return;try{const data=await api(`/api/flows/${flowId}/versions`);setVersions(data.versions||[]);}catch(e){notify(e.message,true);}}
 useEffect(()=>{if(flow&&!demo){if(tab==='executions')refreshRuns();if(tab==='versions')refreshVersions();}},[tab,!!flow]);
 async function executeRun(executionMode=mode,untilNodeId){
  if(running)return;if(demo&&executionMode==='live'){notify('Live runs are available only in the authenticated server workspace',true);return;}
  const problems=validateGraph(graph,NODE_TYPES,{forRun:true,mode:executionMode});if(problems.some(i=>i.severity==='error')){setModal('validation');notify('Resolve validation errors before execution',true);return;}
  try{await saveCurrent();}catch(e){notify(`Run stopped: ${e.message}`,true);return;}
  setRunning(true);setShowConsole(true);setTab('editor');setRun({status:'running',mode:executionMode,logs:[]});abort.current=new AbortController();const start=Date.now();
  try{
   let result;
   if(demo){result=await executeWorkflow(graph,{mode:'test',input:flow.testInput||{},variables:flow.variables||{},definitions:NODE_TYPES,untilNodeId,signal:abort.current.signal,concurrency:flow.settings?.concurrency||3,timeoutMs:flow.settings?.timeoutMs||90000,onLog:async log=>{setRun(r=>({...r,logs:[...(r?.logs||[]),log]}));await new Promise(resolve=>setTimeout(resolve,90));}});result._id=uid('run');const historyRuns=[result,...runs].slice(0,20);setRuns(historyRuns);localStorage.setItem(`${DEMO_KEY}-runs`,JSON.stringify(historyRuns));}
   else {
    let polling=false;livePoll.current=setInterval(async()=>{if(polling)return;polling=true;try{const list=await api(`/api/flows/${flowId}/runs?limit=1`);const recent=list.runs?.[0];if(recent&&new Date(recent.startedAt).getTime()>=start-1000){const detail=await api(`/api/flows/${flowId}/runs/${recent._id}`);if(mounted.current)setRun(detail.run);}}catch{}finally{polling=false;}},1300);
    const response=await api(`/api/flows/${flowId}/run`,{method:'POST',body:JSON.stringify({mode:executionMode,input:flow.testInput||{},untilNodeId})});result=response.run;refreshRuns();
   }
   setRun(result);notify(result.status==='success'?`${executionMode==='test'?'Test':'Live run'} completed successfully`:result.status==='completed_with_errors'?'Run completed with handled errors':result.error||`Run ${result.status}`,result.status==='failed');
  }catch(e){setRun(r=>({...r,status:'failed',error:e.message}));notify(e.message,true);}finally{clearInterval(livePoll.current);setRunning(false);}
 }
 function requestRun(untilNodeId){if(mode==='live')setConfirm({title:'Execute live actions?',message:'This run can send messages, publish content, call external APIs and use paid AI providers. Test mode uses fixtures; live mode does not. Check recipients and credentials first.',action:()=>{setConfirm(null);executeRun('live',untilNodeId);}});else executeRun('test',untilNodeId);}
 async function cancelRun(){if(demo){abort.current?.abort();notify('Cancellation requested');}else try{const data=await api(`/api/flows/${flowId}/cancel`,{method:'POST'});notify(data.message);}catch(e){notify(e.message,true);}}
 async function openRun(value){try{const result=demo?value:(await api(`/api/flows/${flowId}/runs/${value._id}`)).run;setRun(result);setShowConsole(true);setTab('editor');}catch(e){notify(e.message,true);}}
 async function checkpoint(){try{await saveCurrent();const label=checkpointName.trim()||`Checkpoint ${dateLabel(new Date())}`;if(demo){const item={_id:uid('version'),label,revision:revision.current,createdAt:new Date().toISOString(),snapshot:JSON.parse(JSON.stringify(latest.current))};const next=[item,...versions].slice(0,25);setVersions(next);localStorage.setItem(`${DEMO_KEY}-versions`,JSON.stringify(next));}else{await api(`/api/flows/${flowId}/versions`,{method:'POST',body:JSON.stringify({label})});await refreshVersions();}setModal(null);setCheckpointName('');notify('Checkpoint saved');}catch(e){notify(e.message,true);}}
 async function restoreVersion(version){try{const item=demo?version:(await api(`/api/flows/${flowId}/versions/${version._id}`)).version;setConfirm({title:`Restore “${item.label}”?`,message:'The snapshot will replace your current draft. Current graph changes can be recovered with Undo until the page closes.',action:()=>replaceFlow(item.snapshot)});}catch(e){notify(e.message,true);}}
 async function changeStatus(status){if(demo){notify('Publishing is disabled in the local demo. Use Test workflow to execute native steps.');return;}try{await saveCurrent();const data=await api(`/api/flows/${flowId}`,{method:'PUT',body:JSON.stringify({status,revision:revision.current})});revision.current=data.flow.revision;updateFlow({status:data.flow.status});savedSignature.current=JSON.stringify({...latest.current,status:data.flow.status});notify(status==='active'?'Workflow active. Webhooks and configured schedules can now trigger it.':'Workflow paused');}catch(e){notify(e.message,true);}}
 function requestPublish(){if(flow.status==='active')setConfirm({title:'Pause this workflow?',message:'New webhook and scheduled runs will be blocked. An already-running execution is not cancelled.',action:()=>{setConfirm(null);changeStatus('paused');}});else setConfirm({title:'Activate this workflow?',message:'After activation, authenticated webhooks and configured cron triggers may execute real actions. Confirm that external destinations, credentials and test results are correct.',action:()=>{setConfirm(null);changeStatus('active');}});}
 async function generateWebhook(){try{await saveCurrent();const data=await api(`/api/flows/${flowId}/webhook`,{method:'POST'});setWebhook({...data,url:window.location.origin+data.path});setModal('webhook');}catch(e){notify(e.message,true);}}
 function rotateWebhook(){setConfirm({title:'Generate a new webhook token?',message:'Any existing webhook token stops working immediately. The new secret is shown only once.',action:()=>{setConfirm(null);generateWebhook();}});}
 const actions=[{label:'Add a sticky note',icon:'StickyNote',run:()=>addNode('utility.note')},{label:'Auto-layout workflow',icon:'Network',run:()=>layout()},{label:'Fit canvas to view',icon:'Scan',run:()=>instance?.fitView({padding:.2,duration:300})},{label:'Test workflow',icon:'Play',run:()=>executeRun('test')},{label:'Save workflow',icon:'Save',run:()=>saveCurrent().catch(e=>notify(e.message,true))},{label:'Export workflow JSON',icon:'Download',run:exportJSON},{label:'Export diagram SVG',icon:'Image',run:exportSVG},{label:'Import workflow JSON',icon:'Upload',run:()=>fileInput.current?.click()},{label:'Open templates',icon:'LayoutTemplate',run:()=>setModal('templates')},{label:'Show validation',icon:'ShieldCheck',run:()=>setModal('validation')},{label:'Save checkpoint',icon:'GitCommitHorizontal',run:()=>setModal('checkpoint')},{label:'Manage credentials',icon:'KeyRound',run:()=>goToSettings('connections')},{label:'Toggle minimap',icon:'Map',run:()=>setShowMinimap(v=>!v)},{label:'Keyboard shortcuts',icon:'Keyboard',run:()=>setModal('shortcuts')}];
 useEffect(()=>{function key(e){const ctrl=e.ctrlKey||e.metaKey;if(ctrl&&e.key.toLowerCase()==='k'){e.preventDefault();setModal(m=>m==='commands'?null:'commands');return;}if(modal||confirm)return;if(ctrl&&e.key.toLowerCase()==='s'){e.preventDefault();saveCurrent().catch(err=>notify(err.message,true));return;}if(e.target.closest?.('input,textarea,select,[contenteditable="true"]'))return;
  if(ctrl&&e.key==='Enter'){e.preventDefault();executeRun('test');}else if(ctrl&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if(ctrl&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}else if(ctrl&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate(nodes.filter(n=>n.selected||n.id===selectedId).map(n=>n.id));}else if(ctrl&&e.key.toLowerCase()==='c'){e.preventDefault();copySelection();}else if(ctrl&&e.key.toLowerCase()==='v'){e.preventDefault();pasteSelection();}else if(ctrl&&e.key.toLowerCase()==='a'){e.preventDefault();setNodes(ns=>ns.map(n=>({...n,selected:true})));}else if(e.key==='Escape'){setSelectedId(null);}else if(e.key.toLowerCase()==='f'){instance?.fitView({padding:.2,duration:300});}else if(e.key==='?'){setModal('shortcuts');}else if(e.key.toLowerCase()==='n'){addNode('utility.note');}}
  window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
 });
 const renderedNodes=useMemo(()=>nodes.map(n=>({...n,data:{...n.data,runtime:run?.logs?.find(l=>l.nodeId===n.id),onAction:(action,id)=>{if(action==='delete')deleteNodes([id]);if(action==='duplicate')duplicate([id]);if(action==='disable'){changeNode(id,{disabled:!nodes.find(n=>n.id===id)?.data.disabled});}}}})),[nodes,edges,run]);
 if(!flow)return <div className="fp fp-app"><Empty icon={loadError?'CircleAlert':'Workflow'} title={loadError?'Could not open workflow':'Opening Flow Studio'} description={loadError||'Loading your canvas and workspace…'}>{loadError?<Link className="fp-btn" href="/dashboard/flows">Back to workflows</Link>:<Icon name="LoaderCircle" className="fp-spin"/>}</Empty></div>;
 return <div className="fp fp-app" data-studio-theme={theme}>
  <header className="fp-topbar"><Link href={demo?'/dashboard/flows':'/dashboard/flows'} className="fp-btn ghost icon" title="Back to workflows" aria-label="Back to workflows"><Icon name="ArrowLeft" size={16}/></Link><Brand/><div className="fp-divider fp-hide-medium"/><div className="fp-grow"><div className="fp-breadcrumb"><span>{flow.folder||'Personal'}</span><Icon name="ChevronRight" size={10}/><span>{demo?'Local sandbox':'Workflow'}</span></div><input className="fp-title-input" aria-label="Workflow name" value={flow.name} maxLength={80} onChange={e=>updateFlow({name:e.target.value})}/></div><div className="fp-save fp-hide-small"><span className="fp-row" style={{gap:5}}><Icon name={saveState==='saving'?'LoaderCircle':saveState==='error'?'CloudOff':saveState==='unsaved'?'CircleDot':'CloudCheck'} size={12} className={saveState==='saving'?'fp-spin':''}/>{saveState==='saving'?'Saving…':saveState==='error'?'Not saved':saveState==='unsaved'?'Unsaved':'All changes saved'}</span></div><div className="fp-top-actions"><span className={`fp-chip fp-hide-small ${flow.status==='active'?'green':''}`}><span className="fp-dot"/>{flow.status}</span><Button icon="Sparkles" variant="small fp-hide-small" onClick={()=>setModal('ai')}>AI builder</Button><Button icon="Save" variant="ghost small fp-hide-small" title="Save (Ctrl+S)" onClick={()=>saveCurrent().catch(e=>notify(e.message,true))}/><Button icon={flow.status==='active'?'Pause':'Upload'} variant="small" disabled={running||demo} onClick={requestPublish}>{flow.status==='active'?'Pause':'Activate'}</Button><Button icon="Play" variant="primary small" disabled={running} onClick={()=>requestRun()}>{mode==='test'?'Test workflow':'Run live'}</Button></div></header>
  <div className="fp-menubar"><div className="fp-tabs">{[['editor','Workflow','Editor'],['executions','History','Executions'],['versions','GitBranch','Versions'],['settings','Settings2','Settings']].map(([key,icon,label])=><button key={key} className={`fp-tab ${tab===key?'active':''}`} onClick={()=>setTab(key)}><Icon name={icon} size={13}/>{label}{key==='executions'&&runs.length>0&&<span className="fp-tab-count">{runs.length}</span>}</button>)}</div><div className="fp-row" style={{gap:5}}><Button variant="ghost small fp-hide-small" icon="KeyRound" onClick={()=>goToSettings('connections')}>Credentials</Button><Button variant="ghost small" icon="Command" onClick={()=>setModal('commands')} title="Command center (Ctrl+K)"><span className="fp-hide-small">Command center</span><kbd className="fp-kbd fp-hide-small">⌘ K</kbd></Button><Button variant="ghost small" icon="Settings2" title="Theme preferences in Settings" onClick={()=>goToSettings('preferences')}/></div></div>
  {demo&&<div className="fp-banner"><Icon name="FlaskConical" size={13}/><span><strong>Local sandbox.</strong> Native steps run in your browser. External actions use labeled fixtures; nothing is sent.</span><div className="fp-spacer"/><span className="fp-hide-small">Saved only on this browser</span></div>}
  {saveError&&<div className="fp-banner error"><Icon name="CloudOff" size={13}/><span className="fp-grow">{saveError}</span><Button variant="ghost small" onClick={exportJSON}>Export unsaved draft</Button><Button variant="ghost small" onClick={()=>saveCurrent().catch(e=>notify(e.message,true))}>Retry</Button></div>}
  <main className="fp-workspace">
   {tab==='editor'&&<>{showLibrary&&<Palette onAdd={addNode} onClose={()=>setShowLibrary(false)}/>}<div className="fp-canvas-column"><div ref={wrapper} className="fp-canvas" onDrop={e=>{e.preventDefault();const type=e.dataTransfer.getData('application/reactflow');if(!type||!instance)return;const bounds=wrapper.current.getBoundingClientRect();const position=instance.project({x:e.clientX-bounds.left,y:e.clientY-bounds.top});addNode(type,position);}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move';}}>
    <ReactFlow nodes={renderedNodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} onInit={setInstance} onNodesChange={changes=>{if(changes.some(c=>c.type==='remove'))remember();baseNodesChange(changes);}} onEdgesChange={changes=>{if(changes.some(c=>c.type==='remove'))remember();baseEdgesChange(changes);}} onNodeDragStart={remember} onConnect={connect} isValidConnection={isValidConnection} onEdgeUpdate={(old,connection)=>{if(isValidConnection(connection)){remember();setEdges(es=>updateEdge(old,connection,es));}}} onNodeClick={(_,node)=>setSelectedId(node.id)} onPaneClick={()=>setSelectedId(null)} onNodeDoubleClick={(_,node)=>setSelectedId(node.id)} onEdgeDoubleClick={(_,edge)=>setEdgeEdit({id:edge.id,label:edge.label||''})} onMove={(_,viewport)=>setZoom(Math.round(viewport.zoom*100))} snapToGrid={snap} snapGrid={[20,20]} minZoom={.15} maxZoom={2} fitView fitViewOptions={{padding:.2,maxZoom:.9}} selectionOnDrag selectionMode={SelectionMode.Partial} panOnDrag={[1,2]} multiSelectionKeyCode={['Meta','Control','Shift']} deleteKeyCode={['Backspace','Delete']} connectionLineStyle={{stroke:'#a99aff',strokeWidth:2}} defaultEdgeOptions={{type:'proEdge'}}>
     <Background gap={24} size={1} color="rgb(var(--color-line))"/>{showMinimap&&<MiniMap pannable zoomable nodeColor={n=>n.data.nodeType==='utility.note'?'#a99262':'#74699c'} maskColor="rgb(var(--color-ink) / .72)" style={{width:135,height:88,bottom:10,right:8}}/>}
    </ReactFlow>
    <div className="fp-canvas-label"><div className="fp-row"><span className="fp-chip purple"><Icon name="Workflow" size={11}/>CANVAS</span><span className="fp-chip">{nodes.filter(n=>n.data.nodeType!=='utility.note').length} steps</span></div><p className="fp-muted">Build something that works for you.</p></div>
    {!nodes.length&&<div className="fp-canvas-empty"><Empty icon="Workflow" title="An empty canvas. Endless possibilities." description="Add your first trigger, pick a template, or describe a workflow to the AI builder."><div className="fp-row"><Button icon="Plus" variant="primary" onClick={()=>addNode('trigger.manual',{x:250,y:230})}>Add a trigger</Button><Button icon="LayoutTemplate" onClick={()=>setModal('templates')}>Browse templates</Button></div></Empty></div>}
    <div className="fp-floating-tools">{!showLibrary&&<Button icon="PanelLeftOpen" variant="ghost small" title="Show node library" onClick={()=>setShowLibrary(true)}/>}<Button icon="Undo2" variant="ghost small" title="Undo (Ctrl+Z)" onClick={undo} disabled={!historyCount.past}/><Button icon="Redo2" variant="ghost small" title="Redo (Ctrl+Shift+Z)" onClick={redo} disabled={!historyCount.future}/><div className="fp-divider" style={{height:17,margin:'0 4px'}}/><Button icon="Minus" variant="ghost small" title="Zoom out" onClick={()=>instance?.zoomOut()}/><button style={{fontSize:10,width:34,color:'var(--fp-muted)'}} onClick={()=>instance?.zoomTo(1)} title="Reset zoom to 100%">{zoom}%</button><Button icon="Plus" variant="ghost small" title="Zoom in" onClick={()=>instance?.zoomIn()}/><Button icon="Scan" variant="ghost small" title="Fit view (F)" onClick={()=>instance?.fitView({padding:.2,duration:300})}/><div className="fp-divider fp-hide-small" style={{height:17,margin:'0 4px'}}/><Button icon="Network" variant="ghost small fp-hide-small" title="Auto-layout" onClick={()=>layout()}/><Button icon="StickyNote" variant="ghost small fp-hide-small" title="Add note (N)" onClick={()=>addNode('utility.note')}/><Button icon="Grid2X2" variant={`${snap?'active':'ghost'} small fp-hide-small`} title="Toggle snap to grid" onClick={()=>setSnap(v=>!v)}/></div>
    <div className="fp-run-float">{running?<Button icon="Square" variant="danger" onClick={cancelRun}>Stop run</Button>:<Button icon="FlaskConical" variant="primary" onClick={()=>{setInputText(JSON.stringify(flow.testInput||{},null,2));setInputError('');setModal('input');}}>Test input <Icon name="ChevronRight" size={13}/></Button>}</div>
   </div>{showConsole&&<RunPanel run={run} running={running} onClose={()=>setShowConsole(false)} onNode={setSelectedId}/>}</div>{selected&&<Inspector node={selected} onChange={changeNode} onDelete={id=>deleteNodes([id])} onDuplicate={id=>duplicate([id])} onClose={()=>setSelectedId(null)} onTest={id=>executeRun('test',id)} log={run?.logs?.find(l=>l.nodeId===selected.id)} demo={demo} running={running}/>}</>}
   {tab==='executions'&&<ExecutionsPanel runs={runs} onOpen={openRun} onRefresh={refreshRuns}/>}
   {tab==='versions'&&<VersionsPanel versions={versions} onCheckpoint={()=>setModal('checkpoint')} onRestore={restoreVersion}/>}
   {tab==='settings'&&<SettingsPanel flow={flow} onChange={updateFlow} onCredentials={()=>goToSettings('connections')} onWebhook={rotateWebhook} demo={demo}/>}
  </main>
  <footer className="fp-bottom-status"><span className="fp-row" style={{color:'var(--fp-green)'}}><span className="fp-dot"/>{running?'Executing':demo?'Local engine ready':'Workspace ready'}</span><span>{nodes.length} nodes · {edges.length} connections</span><button className="fp-row" onClick={()=>setModal('validation')} style={{color:issues.some(i=>i.severity==='error')?'var(--fp-orange)':'var(--fp-muted)'}}><Icon name="ShieldCheck" size={11}/>{issues.length?`${issues.length} checks to review`:'Validation passed'}</button><div className="fp-spacer"/><button className="fp-hide-small" onClick={()=>setModal('templates')}>Templates</button><button className="fp-hide-small" onClick={()=>fileInput.current?.click()}>Import</button><button className="fp-hide-small" onClick={exportJSON}>Export</button><select aria-label="Execution mode" value={mode} disabled={running} onChange={e=>setMode(e.target.value)} style={{width:85,padding:'0 5px',border:0,fontSize:10,background:'transparent'}}><option value="test">Test mode</option><option value="live" disabled={demo}>Live mode</option></select><button onClick={()=>setModal('shortcuts')} title="Keyboard shortcuts"><Icon name="Keyboard" size={13}/></button></footer>
  <input ref={fileInput} type="file" accept=".json,application/json" style={{display:'none'}} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const value=importWorkflow(await file.text(),NODE_TYPES);setConfirm({title:'Import this workflow?',message:'The imported graph replaces this draft. Credential connections are not carried between workspaces. You can Undo the replacement.',action:()=>replaceFlow(value)});}catch(err){notify(err.message,true);}}}/>
  {modal==='templates'&&<TemplateModal onClose={()=>setModal(null)} onPick={chooseTemplate}/>}
  {modal==='commands'&&<CommandModal onClose={()=>setModal(null)} actions={actions} onAdd={addNode}/>}
  {modal==='credentials'&&<CredentialModal onClose={()=>setModal(null)} demo={demo} notify={notify}/>}
  {modal==='ai'&&<AIBuilderModal onClose={()=>setModal(null)} demo={demo} notify={notify} onApply={value=>{setModal(null);setConfirm({title:'Replace with this AI draft?',message:'The generated graph is a draft, not a verified automation. Review every node and credential before a live run.',action:()=>replaceFlow(value)});}}/>}
  {modal==='validation'&&<Modal title="Workflow health check" subtitle="Validation checks graph structure, fields, routes and connector readiness." onClose={()=>setModal(null)}><div className="fp-issues">{issues.length?issues.map((issue,index)=><div className="fp-issue" key={index}><Icon name={issue.severity==='error'?'CircleAlert':'TriangleAlert'} className={issue.severity==='error'?'fp-status-failed':'fp-muted'}/><button onClick={()=>{if(issue.nodeId){setModal(null);focusNode(issue.nodeId);}}}><strong style={{display:'block',fontSize:10,marginBottom:3}}>{issue.nodeId?nodes.find(n=>n.id===issue.nodeId)?.data.label||issue.nodeId:'Workflow'}</strong>{issue.message}</button><span className={`fp-chip ${issue.severity==='error'?'red':'orange'}`}>{issue.severity}</span></div>):<Empty icon="ShieldCheck" title="Ready for a test run" description="No structural or configuration errors were found. External credentials and provider availability are checked during live execution."/>}</div></Modal>}
  {modal==='input'&&<Modal title="Test input" subtitle="This JSON becomes the trigger output. Try a score below 70 to test the other lead-routing branch." onClose={()=>setModal(null)} footer={<><Button onClick={()=>setModal(null)}>Cancel</Button><Button icon="Check" variant="primary" onClick={()=>{try{const value=parseJSON(inputText,'Test input');updateFlow({testInput:value});setInputError('');setModal(null);notify('Test input updated. Press Test workflow to run.');}catch(e){setInputError(e.message);}}}>Apply input</Button></>}><div className="fp-field"><label>Input payload (JSON)</label><textarea className="fp-code" rows={12} aria-label="Test input JSON" value={inputText} onChange={e=>setInputText(e.target.value)}/>{inputError&&<small className="fp-error">{inputError}</small>}</div></Modal>}
  {modal==='checkpoint'&&<Modal title="Save a checkpoint" subtitle="Keep a named snapshot before changing your workflow." onClose={()=>setModal(null)} footer={<Button icon="GitCommitHorizontal" variant="primary" onClick={checkpoint}>Save checkpoint</Button>}><div className="fp-field"><label>Version label</label><input autoFocus value={checkpointName} maxLength={120} onChange={e=>setCheckpointName(e.target.value)} placeholder="Before adding CRM integration" aria-label="Checkpoint label"/></div></Modal>}
  {modal==='webhook'&&webhook&&<Modal title="Webhook token generated" subtitle="Copy this secret now. Closing this dialog hides it permanently; rotate the token to get a new one." onClose={()=>{setModal(null);setWebhook(null);}}><div className="fp-stack"><JsonView value={{url:webhook.url,method:'POST',headers:{Authorization:`Bearer ${webhook.token}`}}} title="PRIVATE WEBHOOK CONFIGURATION"/><div className="fp-expression-hint">Activate the workflow before sending a request. This endpoint returns a run ID and outcome; it does not echo internal step outputs. Keep the token on a trusted server.</div><Button icon="Copy" onClick={async()=>{try{await navigator.clipboard.writeText(`curl -X POST '${webhook.url}' -H 'Authorization: Bearer ${webhook.token}' -H 'Content-Type: application/json' -d '${JSON.stringify(flow.testInput||{})}'`);notify('Webhook example copied');}catch{notify('Clipboard unavailable. Copy the JSON manually.',true);}}}>Copy cURL example</Button></div></Modal>}
  {modal==='shortcuts'&&<Modal title="Stay in flow" subtitle="Keyboard shortcuts for the canvas. Shortcuts do not interfere with text editing." onClose={()=>setModal(null)}><div className="fp-shortcuts">{[['Command center','Ctrl / ⌘ K'],['Save workflow','Ctrl / ⌘ S'],['Test workflow','Ctrl / ⌘ Enter'],['Undo','Ctrl / ⌘ Z'],['Redo','Ctrl / ⌘ Shift Z'],['Duplicate selection','Ctrl / ⌘ D'],['Copy / paste nodes','Ctrl / ⌘ C / V'],['Select all nodes','Ctrl / ⌘ A'],['Fit canvas','F'],['Add sticky note','N'],['Delete selection','Delete / Backspace'],['Close selection','Escape']].map(([label,key])=><div key={label}><span>{label}</span><kbd className="fp-kbd">{key}</kbd></div>)}</div><p className="fp-muted" style={{fontSize:11,marginTop:20}}>Drag on the canvas to box-select. Middle/right-drag to pan. Scroll to zoom. Double-click an edge to edit its label.</p></Modal>}
  {edgeEdit&&<Modal title="Connection settings" onClose={()=>setEdgeEdit(null)} footer={<><Button variant="danger" icon="Trash2" onClick={()=>{remember();setEdges(es=>es.filter(e=>e.id!==edgeEdit.id));setEdgeEdit(null);}}>Delete connection</Button><Button variant="primary" onClick={()=>{remember();setEdges(es=>es.map(e=>e.id===edgeEdit.id?{...e,label:edgeEdit.label}:e));setEdgeEdit(null);}}>Save label</Button></>}><div className="fp-field"><label>Connection label</label><input value={edgeEdit.label} onChange={e=>setEdgeEdit({...edgeEdit,label:e.target.value})} maxLength={80} aria-label="Connection label" placeholder="e.g. Qualified lead"/></div></Modal>}
  {confirm&&<Modal title={confirm.title} onClose={()=>setConfirm(null)} footer={<><Button onClick={()=>setConfirm(null)}>Cancel</Button><Button variant="primary" onClick={confirm.action}>Confirm</Button></>}><p style={{fontSize:13,color:'var(--fp-muted)',lineHeight:1.9}}>{confirm.message}</p></Modal>}
  {toast&&<div className={`fp-toast ${toast.error?'error':''}`} role="status"><Icon name={toast.error?'CircleAlert':'CircleCheck'} size={16} style={{color:toast.error?'var(--fp-red)':'var(--fp-green)'}}/>{toast.message}<Button icon="X" variant="ghost small" title="Dismiss notification" onClick={()=>setToast(null)}/></div>}
 </div>;
}
export default function FlowStudio(props){return <ReactFlowProvider><GraphEditor {...props}/></ReactFlowProvider>;}
