'use client';
import { useEffect, useState } from 'react';
import { getNodeTypeDef, fieldIsVisible } from '../nodeTypesConfig';
import { parseJSON } from '../../../lib/flowPro/expressions.mjs';
import { Icon, NodeIcon, Button, JsonView, api } from './UI';
function ConnectedSelect({field,value,onChange,demo}){
 const [items,setItems]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let cancelled=false;if(demo)return;setLoading(true);api(field.type==='credential'?'/api/flow-credentials':`/api/connections?platform=${encodeURIComponent(field.platform||'google')}`).then(data=>{if(!cancelled)setItems(data.credentials||data.connections||[]);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[field.type,field.platform,demo]);
 if(demo)return <div className="fp-expression-hint">Credentials are available in the signed-in workspace. Test mode does not need an account.</div>;
 return <><select value={value||''} onChange={e=>onChange(e.target.value)} aria-label={field.label}><option value="">{loading?'Loading…':'Choose a saved account…'}</option>{items.map(c=><option key={c._id} value={c._id}>{c.name||c.accountName||c.accountId} {c.type?`· ${c.type}`:''}</option>)}</select>{error&&<small className="fp-error">{error}</small>}<small>{field.type==='credential'?'Manage encrypted credentials in Settings → Connections.':'Connect Google or social accounts from the existing dashboard Settings page.'}</small></>;
}
export function Field({field,value,onChange,demo=false}){
 const v=value??field.default??'';let error='';
 if(field.type==='json'&&v&&typeof v==='string'&&!/^\s*\{\{/.test(v)){try{parseJSON(v);}catch(e){error='Invalid JSON: '+e.message.replace(/^JSON: /,'');}}
 return <div className="fp-field"><label>{field.label}{field.required&&<span style={{color:'var(--fp-accent)'}}>*</span>}</label>{['connection','credential'].includes(field.type)?<ConnectedSelect field={field} value={value} onChange={onChange} demo={demo}/>:field.type==='select'?<select aria-label={field.label} value={v} onChange={e=>onChange(e.target.value)}>{field.options.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>:field.type==='json'||field.type==='textarea'?<textarea aria-label={field.label} className={field.type==='json'?'fp-code':''} spellCheck={false} value={typeof v==='object'?JSON.stringify(v,null,2):v} onChange={e=>onChange(e.target.value)} placeholder={field.placeholder} rows={field.type==='json'?6:4}/>:<input aria-label={field.label} type={field.type==='number'?'number':field.type==='time'?'time':'text'} min={field.min} max={field.max} value={v} onChange={e=>onChange(field.type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)} placeholder={field.placeholder}/>}<small className={error?'fp-error':''}>{error||field.helpText}</small></div>;
}
export default function Inspector({node,onChange,onDelete,onDuplicate,onClose,onTest,log,demo,running}){
 const [tab,setTab]=useState('parameters'),[pinText,setPinText]=useState(''),[pinError,setPinError]=useState('');
 useEffect(()=>{setTab('parameters');setPinText(JSON.stringify(node?.data.pinnedData??log?.output??{},null,2));setPinError('');},[node?.id]);
 if(!node)return null;const def=getNodeTypeDef(node.data.nodeType),config=node.data.config||{},settings=node.data.settings||{};
 const changeConfig=(key,value)=>onChange(node.id,{config:{...config,[key]:value}});const changeSettings=(key,value)=>onChange(node.id,{settings:{...settings,[key]:value}});
 return <aside className="fp-inspector" aria-label="Node inspector"><div className="fp-inspector-head"><div className="fp-row"><NodeIcon definition={def}/><div className="fp-grow"><h3>{def?.label||node.data.nodeType}</h3><span className="fp-chip" style={{marginTop:4}}>NODE CONFIGURATION</span></div><Button icon="X" variant="ghost" title="Close inspector" onClick={onClose}/></div><p>{def?.description}</p></div><div className="fp-tabs">{[['parameters','Settings2','Parameters'],['settings','SlidersHorizontal','Settings'],['data','Braces','Data']].map(([key,icon,label])=><button className={`fp-tab ${tab===key?'active':''}`} key={key} onClick={()=>setTab(key)}><Icon name={icon} size={12}/>{label}</button>)}</div><div className="fp-inspector-body">
  {tab==='parameters'&&<><Field field={{key:'label',label:'Step name',type:'text',placeholder:def?.label}} value={node.data.label||''} onChange={label=>onChange(node.id,{label})}/>{def?.capability==='planned'&&<div className="fp-banner error" style={{borderRadius:8,marginBottom:15}}>This inherited connector has no live executor. Use HTTP Request with a supported API instead.</div>}{(def?.configSchema||[]).filter(f=>fieldIsVisible(f,{...Object.fromEntries((def.configSchema||[]).map(f=>[f.key,f.default])),...config})).map(field=><Field key={field.key} field={field} value={config[field.key]} onChange={value=>changeConfig(field.key,value)} demo={demo}/>)}{!(def?.configSchema?.length)&&<p className="fp-muted" style={{fontSize:11,marginBottom:18}}>This step works without additional parameters.</p>}{node.data.nodeType!=='utility.note'&&<div className="fp-expression-hint"><div className="fp-row" style={{marginBottom:4}}><Icon name="Braces" size={12}/><strong>Dynamic values</strong></div><code>{'{{ $json.email }}'}</code> · input field<br/><code>{'{{ $vars.brand }}'}</code> · workflow variable<br/><code>{'{{ $item.name }}'}</code> · current item<br/><code>{'{{ $json.name ?? "Guest" }}'}</code><div style={{marginTop:5,opacity:.75}}>Expressions read data paths only; arbitrary JavaScript is not executed.</div></div>}<div className="fp-node-id">ID: {node.id}</div></>}
  {tab==='settings'&&<><div className="fp-section-title">Execution behavior</div><label className="fp-checkbox"><input type="checkbox" checked={!!node.data.disabled} onChange={e=>onChange(node.id,{disabled:e.target.checked})}/><span><strong>Disable this node</strong><br/><span className="fp-muted">Pass the input through without running the action.</span></span></label><Field field={{label:'Execute',type:'select',options:[{value:'once',label:'Once with the complete input'},{value:'each',label:'Once per item (up to 100)'}],default:'once'}} value={settings.executionMode} onChange={v=>changeSettings('executionMode',v)}/><Field field={{label:'On error',type:'select',options:[{value:'stop',label:'Stop workflow'},{value:'continue',label:'Continue with error data'},{value:'branch',label:'Route to error output'}],default:'stop'}} value={settings.onError} onChange={v=>changeSettings('onError',v)}/><div className="fp-row" style={{alignItems:'flex-start'}}><Field field={{label:'Retries (0–3)',type:'number',default:0,min:0,max:3}} value={settings.retries} onChange={v=>changeSettings('retries',v)}/><Field field={{label:'Retry delay (ms)',type:'number',default:250,min:0,max:1500}} value={settings.retryDelayMs} onChange={v=>changeSettings('retryDelayMs',v)}/></div><Field field={{label:'Step timeout (ms)',type:'number',default:15000,min:100,max:30000,helpText:'Timeouts are not automatically retried, since an external action may already have completed.'}} value={settings.timeoutMs} onChange={v=>changeSettings('timeoutMs',v)}/><Field field={{label:'Internal notes',type:'textarea'}} value={node.data.notes||''} onChange={notes=>onChange(node.id,{notes})}/></>}
  {tab==='data'&&<div className="fp-stack">{log?<><div className="fp-row fp-between"><span className={`fp-chip ${log.status==='failed'?'red':'green'}`}>{log.status}</span>{log.mock&&<span className="fp-chip orange">Mock output</span>}</div><JsonView value={log.input} title="INPUT"/><JsonView value={log.output} title="OUTPUT"/>{log.error&&<div className="fp-expression-hint" style={{color:'var(--fp-red)'}}>{log.error}</div>}</> :<p className="fp-muted" style={{fontSize:11}}>Run a test to inspect the input and output of this node.</p>}<div className="fp-field"><label><Icon name="Pin" size={13}/>Pinned test data</label><textarea className="fp-code" value={pinText} onChange={e=>setPinText(e.target.value)} aria-label="Pinned JSON data"/><small>Only test runs use pins. Live runs always execute the node.</small>{pinError&&<small className="fp-error">{pinError}</small>}</div><div className="fp-row"><Button icon="Pin" variant={node.data.pinned?'active small':'small'} onClick={()=>{try{onChange(node.id,{pinned:true,pinnedData:parseJSON(pinText,'Pinned data')});setPinError('');}catch(e){setPinError(e.message);}}}>Pin data</Button>{node.data.pinned&&<Button icon="PinOff" variant="ghost small" onClick={()=>onChange(node.id,{pinned:false})}>Unpin</Button>}{log&&<Button variant="ghost small" onClick={()=>setPinText(JSON.stringify(log.output??null,null,2))}>Use output</Button>}</div></div>}
 </div><div className="fp-inspector-footer"><Button icon="Play" variant="primary small" onClick={()=>onTest(node.id)} disabled={running||node.data.nodeType==='utility.note'}>Test to step</Button><div className="fp-spacer"/><Button icon="Copy" variant="ghost small" title="Duplicate node" onClick={()=>onDuplicate(node.id)}/><Button icon="Trash2" variant="ghost danger small" title="Delete node" onClick={()=>onDelete(node.id)}/></div></aside>;
}
