'use client';
import { useMemo, useState } from 'react';
import { NODE_TYPES, NODE_CATEGORIES } from '../nodeTypesConfig';
import { Icon, NodeIcon, Button } from './UI';
const groups=[['all','All nodes'],['trigger','Triggers'],['ai','AI'],['data','Data'],['logic','Logic'],['integration','APIs'],['google','Google'],['platform','Social'],['utility','Tools']];
export default function Palette({onAdd,onClose}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState('all');
 const filtered=useMemo(()=>NODE_TYPES.filter(n=>(category==='all'||n.category===category)&&`${n.label} ${n.description} ${n.type}`.toLowerCase().includes(search.toLowerCase())),[search,category]);
 return <aside className="fp-library" aria-label="Node library"><div className="fp-library-head"><div className="fp-row fp-between"><h3>Node library</h3><div className="fp-row" style={{gap:5}}><span className="fp-chip">{NODE_TYPES.length}</span><Button icon="PanelLeftClose" variant="ghost small" title="Hide node library" onClick={onClose}/></div></div><p className="fp-muted" style={{fontSize:10,marginTop:5}}>Everything your next workflow needs.</p><div className="fp-search"><Icon name="Search" size={13}/><input aria-label="Search nodes" placeholder="Search nodes, actions…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="fp-category-tabs">{groups.map(([key,label])=><button key={key} className={`fp-category ${category===key?'active':''}`} onClick={()=>setCategory(key)}>{label}</button>)}</div><div className="fp-library-list">{Object.entries(NODE_CATEGORIES).sort(([a],[b])=>groups.findIndex(g=>g[0]===a)-groups.findIndex(g=>g[0]===b)).map(([key,group])=>{const list=filtered.filter(n=>n.category===key);if(!list.length)return null;return <section key={key}><div className="fp-group-title"><span>{group.label}</span><span>{list.length}</span></div>{list.map(def=><div key={def.type} className="fp-node-option" draggable onDragStart={e=>{e.dataTransfer.setData('application/reactflow',def.type);e.dataTransfer.effectAllowed='move';}} onClick={()=>onAdd(def.type)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onAdd(def.type);}}} role="button" tabIndex={0} title={`${def.label}: ${def.description}`}><NodeIcon definition={def} size={15}/><div className="fp-grow"><div className="fp-node-option-title">{def.label}</div><div className="fp-node-option-description">{def.capability==='planned'?'Placeholder · not available for live execution':def.description}</div></div><span className="fp-option-plus"><Icon name="Plus" size={12}/></span></div>)}</section>;})}{!filtered.length&&<p className="fp-muted" style={{padding:15,fontSize:11}}>No nodes match “{search}”.</p>}</div><div className="fp-library-footer"><Icon name="MousePointer2" size={14}/><span>Drag onto canvas, or click to add.</span></div></aside>;
}
