'use client';
import { useEffect, useState } from 'react';
import {useSettings} from '@/lib/SettingsContext';
import { Icon, Button, Modal, Empty, JsonView, duration, dateLabel, api, downloadJSON, NodeIcon } from './UI';
import { Field } from './Inspector';
import { NODE_TYPES, getNodeTypeDef } from '../nodeTypesConfig';
import { FLOW_TEMPLATES } from '../../../lib/flowTemplates';
import { parseJSON } from '../../../lib/flowPro/expressions.mjs';
export function RunPanel({run,running,onClose,onNode,expanded=false}){
 const [selected,setSelected]=useState(null),[filter,setFilter]=useState('all');const logs=run?.logs||[];const log=logs.find(l=>l.nodeId===selected)||logs.at(-1);const shown=logs.filter(l=>filter==='all'||l.status===filter);
 return <section className="fp-run-panel" style={expanded?{height:'100%'}:{}}><div className="fp-panel-head"><Icon name="Terminal" size={14}/><h3>Execution console</h3>{run&&<span className={`fp-chip ${run.status==='success'?'green':run.status==='failed'?'red':'purple'}`}>{running?'Running':run.status?.replaceAll('_',' ')}</span>}{run?.billing&&<span className="fp-chip purple">{run.billing.status==='reserved'?`${run.billing.reserved} cr reserved`:`${run.billing.charged} cr used · ${run.billing.refunded} returned`}</span>}{run?.mode&&<span className="fp-chip orange">{run.mode==='test'?'Test mode':'Live run'}</span>}<div className="fp-spacer"/><select aria-label="Filter run steps" value={filter} onChange={e=>setFilter(e.target.value)} style={{width:105,padding:'3px 6px',fontSize:10}}><option value="all">All steps</option><option value="success">Success</option><option value="failed">Failed</option><option value="skipped">Skipped</option></select>{run&&<Button icon="Download" title="Download execution JSON" variant="ghost small" onClick={()=>downloadJSON(run,`execution-${run._id||'test'}.json`)}/>}<Button icon="X" title="Close execution console" variant="ghost small" onClick={onClose}/></div>{running&&<div className="fp-progress"/>}<div className="fp-run-content"><div className="fp-step-list">{shown.map((l,i)=><button key={`${l.nodeId}-${i}`} className={`fp-step ${log?.nodeId===l.nodeId?'active':''}`} onClick={()=>{setSelected(l.nodeId);onNode?.(l.nodeId);}}><Icon name={l.status==='success'?'CircleCheck':l.status==='failed'?'CircleAlert':'CircleMinus'} size={13} className={`fp-status-${l.status}`}/><span className="fp-grow" style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{l.nodeLabel||getNodeTypeDef(l.nodeType)?.label||l.nodeType}</span><span className="fp-step-time">{l.credits??0} cr · {duration(l.durationMs)}</span></button>)}{!logs.length&&<p className="fp-muted" style={{fontSize:10,padding:9}}>Waiting for workflow steps…</p>}</div><div className="fp-log-detail">{log?<div className="fp-stack" style={{gap:10}}><div className="fp-row fp-between"><span style={{fontSize:11}}>{log.message||log.error||'Step output'}</span><span className="fp-muted" style={{fontSize:9,whiteSpace:'nowrap'}}>{log.attempts||0} attempt(s)</span></div>{log.mock&&<span className="fp-chip orange" style={{alignSelf:'flex-start'}}>Fixture only · no external call</span>}<JsonView value={log.output} title="OUTPUT"/><JsonView value={log.input} title="INPUT"/></div>:<Empty icon="Terminal" title={running?'Executing your workflow':'No execution data'} description="Each executed step will appear here with its input, output, timing and errors."/>}</div></div></section>;
}
export function ExecutionsPanel({runs,onOpen,onRefresh}){
 const [filter,setFilter]=useState('all');const filtered=runs.filter(r=>filter==='all'||r.status===filter);
 return <section className="fp-full-page"><div className="fp-page-heading"><div><h2>Execution history</h2><p className="fp-muted" style={{fontSize:11,marginTop:7}}>Inspect outcomes, timing and step-level data. Test and live runs are labeled separately.</p></div><Button icon="RefreshCw" onClick={onRefresh}>Refresh</Button></div><div className="fp-row" style={{marginBottom:18}}>{['all','success','failed','completed_with_errors','cancelled'].map(s=><Button key={s} variant={`small ${filter===s?'active':''}`} onClick={()=>setFilter(s)}>{s.replaceAll('_',' ')}</Button>)}</div>{!filtered.length?<Empty icon="History" title="No matching runs" description="Execute a workflow to build a real run history. No sample metrics are displayed."/>:<div className="fp-table-wrap"><table className="fp-table"><thead><tr><th>Execution</th><th>Status</th><th>Mode</th><th>Started</th><th>Duration</th><th>Steps</th><th>Credits</th><th/></tr></thead><tbody>{filtered.map(r=><tr key={r._id} onClick={()=>onOpen(r)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')onOpen(r);}}><td className="fp-mono">#{String(r._id).slice(-8)}</td><td><span className={`fp-chip ${r.status==='success'?'green':r.status==='failed'?'red':'orange'}`}>{r.status?.replaceAll('_',' ')}</span></td><td>{r.mode||'live'}</td><td>{dateLabel(r.startedAt)}</td><td>{duration(r.durationMs)}</td><td>{r.summary?.total??r.logs?.length??'—'}</td><td>{r.billing?.charged??'—'}</td><td><Icon name="ArrowUpRight" size={14}/></td></tr>)}</tbody></table></div>}</section>;
}
export function VersionsPanel({versions,onCheckpoint,onRestore}){return <section className="fp-full-page"><div className="fp-page-heading"><div><h2>Version history</h2><p className="fp-muted" style={{fontSize:11,marginTop:7}}>Named checkpoints and publish snapshots. The latest 25 are retained.</p></div><Button icon="GitCommitHorizontal" variant="primary" onClick={onCheckpoint}>Save checkpoint</Button></div>{versions.length?<div className="fp-version-list">{versions.map((v,i)=><div className="fp-version" key={v._id}><div className="fp-node-icon"><Icon name="GitCommitHorizontal"/></div><div className="fp-grow"><h3>{v.label}</h3><p className="fp-muted" style={{fontSize:10,marginTop:5}}>Revision {v.revision} · {dateLabel(v.createdAt)}</p></div>{i===0&&<span className="fp-chip purple">Latest checkpoint</span>}<Button icon="RotateCcw" variant="small" onClick={()=>onRestore(v)}>Restore</Button></div>)}</div>:<Empty icon="GitBranch" title="Your first checkpoint awaits" description="Save a named version before a significant edit. Restores open as drafts and can be tested before publishing."/>}</section>;}
function JSONSetting({label,value,onChange,help}){const [text,setText]=useState(JSON.stringify(value??{},null,2)),[error,setError]=useState('');useEffect(()=>setText(JSON.stringify(value??{},null,2)),[value]);return <div className="fp-field"><label>{label}</label><textarea className="fp-code" value={text} aria-label={label} onChange={e=>setText(e.target.value)} onBlur={()=>{try{const parsed=parseJSON(text,label);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('Use a JSON object');onChange(parsed);setError('');}catch(e){setError(e.message);}}}/><small className={error?'fp-error':''}>{error||help}</small></div>;}
export function SettingsPanel({flow,onChange,onCredentials,onWebhook,demo}){return <section className="fp-settings-page"><div className="fp-settings-grid"><div className="fp-card"><h3>Workflow details</h3><p>Give this workflow context for your future self.</p><Field field={{label:'Name',type:'text'}} value={flow.name} onChange={name=>onChange({name})}/><Field field={{label:'Description',type:'textarea'}} value={flow.description} onChange={description=>onChange({description})}/><Field field={{label:'Folder',type:'text'}} value={flow.folder||'Personal'} onChange={folder=>onChange({folder})}/><Field field={{label:'Tags (comma-separated)',type:'text'}} value={(flow.tags||[]).join(', ')} onChange={value=>onChange({tags:value.split(',').map(v=>v.trim()).filter(Boolean).slice(0,10)})}/><label className="fp-checkbox"><input type="checkbox" checked={!!flow.starred} onChange={e=>onChange({starred:e.target.checked})}/>Star this workflow</label></div><div className="fp-card"><h3>Execution policy</h3><p>Bounded execution, with explicit failure behavior.</p><Field field={{label:'Parallel steps (1–6)',type:'number',default:3,min:1,max:6}} value={flow.settings?.concurrency} onChange={concurrency=>onChange({settings:{...flow.settings,concurrency}})}/><Field field={{label:'Workflow timeout (milliseconds)',type:'number',default:90000,min:1000,max:90000}} value={flow.settings?.timeoutMs} onChange={timeoutMs=>onChange({settings:{...flow.settings,timeoutMs}})}/><div className="fp-expression-hint">One active run per workflow. Graphs are capped at 200 nodes and 500 connections. This runner is request-bound, not a durable queue. Long-running jobs need a separate worker.</div></div><div className="fp-card"><h3>Workflow variables</h3><p>Reference reusable values with <code>{'{{ $vars.key }}'}</code>.</p><JSONSetting label="Variables (JSON)" value={flow.variables} onChange={variables=>onChange({variables})} help="Do not store secrets here. Variables are included in workflow exports."/></div><div className="fp-card"><h3>Connections & triggers</h3><p>Credentials stay on the server, encrypted at rest.</p><div className="fp-stack"><Button icon="KeyRound" onClick={onCredentials}>Manage credentials</Button><Button icon="Webhook" disabled={demo} onClick={onWebhook}>Generate / rotate webhook token</Button><div className="fp-expression-hint">Webhook triggers require an active workflow and a Bearer token. Schedules require an external cron to call <code>/api/cron/flows</code>. HTTP hosts must be approved in server configuration.</div></div></div></div></section>;}
export function TemplateModal({onClose,onPick}){const [query,setQuery]=useState('');const list=[...FLOW_TEMPLATES].sort((a,b)=>(b.native?1:0)-(a.native?1:0)).filter(t=>`${t.name} ${t.description}`.toLowerCase().includes(query.toLowerCase()));return <Modal wide title="Start with a proven pattern" subtitle="Editable workflow templates. Native templates run without external accounts." onClose={onClose}><div className="fp-search" style={{margin:'0 0 20px'}}><Icon name="Search" size={14}/><input aria-label="Search templates" placeholder="Search sales, AI, APIs, data…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="fp-template-grid">{list.map(t=><button key={t.id} className="fp-template-card" onClick={()=>onPick(t)}><div className="fp-row fp-between" style={{width:'100%'}}><div className="fp-node-icon"><Icon name={t.icon}/></div><span className={`fp-chip ${t.native?'green':'orange'}`}>{t.native?'Native':'Setup required'}</span></div><h3>{t.name}</h3><p>{t.description}</p><div className="fp-template-foot"><span>{t.nodes.filter(n=>n.type!=='utility.note').length} steps</span><span>{t.category||'Connected workflow'}</span><Icon name="ArrowUpRight" size={13}/></div></button>)}</div></Modal>;}
export function CommandModal({onClose,actions,onAdd}){const[query,setQuery]=useState(''),[index,setIndex]=useState(0);const items=[...actions.map(a=>({...a,kind:'Action'})),...NODE_TYPES.map(n=>({label:n.label,icon:n.icon,kind:n.category,run:()=>onAdd(n.type)}))].filter(i=>`${i.label} ${i.kind}`.toLowerCase().includes(query.toLowerCase())).slice(0,30);return <Modal title="Command center" subtitle="Find an action or add any node without leaving the keyboard." onClose={onClose}><input autoFocus placeholder="Type a command or search nodes…" aria-label="Command search" value={query} onChange={e=>{setQuery(e.target.value);setIndex(0);}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setIndex(i=>Math.min(i+1,items.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,i-1));}if(e.key==='Enter'&&items[index]){e.preventDefault();onClose();items[index].run();}}}/><div className="fp-command-list">{items.map((item,i)=><button className={`fp-command ${index===i?'selected':''}`} key={`${item.kind}-${item.label}`} onMouseEnter={()=>setIndex(i)} onClick={()=>{onClose();item.run();}}><Icon name={item.icon}/>{item.label}<small>{item.kind}</small></button>)}</div></Modal>;}
export function CredentialModal({onClose,demo,notify}){const[items,setItems]=useState([]),[form,setForm]=useState({name:'',type:'bearer',secret:'',headerName:'X-API-Key'}),[busy,setBusy]=useState(false),[remove,setRemove]=useState(null);async function refresh(){try{const data=await api('/api/flow-credentials');setItems(data.credentials);}catch(e){notify(e.message,true);}}useEffect(()=>{if(!demo)refresh();},[demo]);return <Modal title="Encrypted credentials" subtitle="Secrets are encrypted with AES-256-GCM and never returned by the list API." onClose={onClose} footer={<Button icon="LockKeyhole" variant="primary" disabled={busy||demo||!form.name||!form.secret} onClick={async()=>{setBusy(true);try{await api('/api/flow-credentials',{method:'POST',body:JSON.stringify(form)});setForm({...form,name:'',secret:''});await refresh();notify('Credential saved securely');}catch(e){notify(e.message,true);}finally{setBusy(false);}}}>{busy?'Saving…':'Save credential'}</Button>}>{demo?<div className="fp-banner" style={{borderRadius:8,marginBottom:20}}>Local demo: no credentials are stored. Open the signed-in workspace to connect services.</div>:null}{items.length>0&&<div className="fp-stack" style={{marginBottom:22,gap:9}}>{items.map(c=><div className="fp-row" key={c._id} style={{border:'1px solid var(--fp-line)',borderRadius:9,padding:10}}><Icon name="KeyRound"/><div className="fp-grow"><strong style={{fontSize:11}}>{c.name}</strong><p className="fp-muted" style={{fontSize:10}}>{c.type} · saved {dateLabel(c.createdAt)}</p></div>{remove===c._id?<><Button variant="small danger" onClick={async()=>{try{await api(`/api/flow-credentials/${c._id}`,{method:'DELETE'});setRemove(null);refresh();}catch(e){notify(e.message,true);}}}>Confirm delete</Button><Button variant="ghost small" onClick={()=>setRemove(null)}>Cancel</Button></>:<Button icon="Trash2" variant="ghost small" title="Delete credential" onClick={()=>setRemove(c._id)}/>}</div>)}</div>}<Field field={{label:'Credential name',type:'text',placeholder:'Production API'}} value={form.name} onChange={name=>setForm({...form,name})}/><Field field={{label:'Credential type',type:'select',options:['bearer','basic','header','slackWebhook','discordWebhook','telegram'].map(value=>({value,label:value}))}} value={form.type} onChange={type=>setForm({...form,type})}/>{form.type==='header'&&<Field field={{label:'Header name',type:'text'}} value={form.headerName} onChange={headerName=>setForm({...form,headerName})}/>}<div className="fp-field"><label>Secret value</label><input type="password" autoComplete="new-password" aria-label="Credential secret" value={form.secret} onChange={e=>setForm({...form,secret:e.target.value})}/><small>{form.type==='basic'?'Format: username:password. ':''}Never paste tokens in a node parameter or workflow variable.</small></div></Modal>;}
export function AIBuilderModal({onClose,onApply,demo,notify}){
 const[prompt,setPrompt]=useState(''),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[quote,setQuote]=useState(null),[priceError,setPriceError]=useState('');
 const {refresh}=useSettings();
 async function price(){try{const data=await api('/api/flows/blueprint');setQuote(data.quote);setPriceError('');}catch(e){setPriceError(e.message);}}
 useEffect(()=>{if(!demo)price();},[demo]);
 async function generate(){setBusy(true);try{const data=await api('/api/flows/blueprint',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({prompt,maxCredits:quote.total})});setDraft(data.draft);notify(`Draft generated · ${data.billing?.charged??0} credits used`);}catch(e){notify(e.message,true);}finally{setBusy(false);refresh();price();}}
 return <Modal title="Build with AI" subtitle="Describe the outcome. Review the generated draft before making live calls." onClose={onClose} footer={<>{draft&&<Button variant="primary" icon="Workflow" onClick={()=>onApply(draft)}>Use this draft</Button>}<Button icon="Sparkles" disabled={demo||busy||prompt.trim().length<10||!quote||quote.overLimit||quote.balance<quote.total} variant={draft?'':'primary'} onClick={generate}>{busy?'Generating…':`${draft?'Regenerate':'Generate draft'} · ${quote?.total??'—'} cr`}</Button></>}>
 {demo&&<div className="fp-banner" style={{marginBottom:15,borderRadius:7}}>The browser sandbox has no provider access. Use the signed-in workspace for AI generation.</div>}
 {priceError&&<p className="fp-error">{priceError} <Button onClick={price}>Retry pricing</Button></p>}
 {quote&&<div className="fp-card" style={{marginBottom:15}}><strong>{quote.total} credits per draft</strong><p>Balance: {quote.balance}. Running the generated workflow is priced separately. Failed draft generation is refunded.</p>{quote.balance<quote.total&&<p className="fp-error">Not enough credits. Open Settings → Plan & Billing.</p>}</div>}
 <div className="fp-field"><label>What should this workflow do?</label><textarea rows={6} aria-label="AI workflow description" placeholder="When a lead arrives, validate name and email, route scores over 70 to the sales queue, then merge and log the result." value={prompt} maxLength={2000} onChange={e=>setPrompt(e.target.value)}/><small>{prompt.length}/2,000 · Generated nodes use only supported types.</small></div>{draft&&<div className="fp-card"><h3>{draft.name}</h3><p>{draft.description}</p><span className="fp-chip purple">{draft.nodes.length} nodes · {draft.edges.length} connections</span><div style={{marginTop:14}}><JsonView value={draft} title="REVIEW GENERATED DRAFT"/></div></div>}
 </Modal>;
}
