'use client';
import { useEffect, useRef, useState } from 'react';
import * as Lucide from 'lucide-react';
export function Icon({name='Workflow',size=16,...props}){const Component=Lucide[name]||Lucide.Workflow;return <Component size={size} strokeWidth={1.7} {...props}/>;}
export function Button({icon,children,variant='',className='',...props}){return <button type="button" className={`fp-btn ${variant} ${!children?'icon':''} ${className}`} aria-label={props['aria-label']||props.title||(typeof children==='string'?children:undefined)} {...props}>{icon&&<Icon name={icon} size={14}/>} {children}</button>;}
export function Brand(){return <div className="fp-brand"><div className="fp-brand-mark"><Icon name="Workflow" size={20}/></div><span>MultiMind<span style={{fontWeight:400,color:'var(--fp-muted)'}}> / flows</span></span></div>;}
export function Empty({icon='Workflow',title,description,children}){return <div className="fp-empty"><div className="fp-empty-icon"><Icon name={icon} size={25}/></div><h3>{title}</h3><p>{description}</p>{children}</div>;}
export function Modal({title,subtitle,children,footer,onClose,wide=false}){
 const ref=useRef(null), closeRef=useRef(onClose); closeRef.current=onClose;
 useEffect(()=>{const before=document.activeElement;const dialog=ref.current;const focusable=()=>[...dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]')];(dialog.querySelector('input:not(:disabled),textarea:not(:disabled),select:not(:disabled)')||focusable()[0])?.focus();function key(e){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeRef.current();}if(e.key==='Tab'){const all=focusable();if(!all.length){e.preventDefault();return;}if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0].focus();}}}dialog.addEventListener('keydown',key);return()=>{dialog.removeEventListener('keydown',key);before?.focus?.();};},[]);
 return <div className="fp-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={ref} className={`fp-modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-label={title}><div className="fp-modal-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><Button icon="X" variant="ghost" title="Close dialog" onClick={onClose}/></div><div className="fp-modal-body">{children}</div>{footer&&<div className="fp-modal-footer">{footer}</div>}</section></div>;
}
export function JsonView({value,title='JSON data'}){
 const [view,setView]=useState('json'),[copied,setCopied]=useState(false);const rows=Array.isArray(value)?value:[value];const table=rows.length>0&&rows.every(v=>v&&typeof v==='object'&&!Array.isArray(v));const columns=table?[...new Set(rows.slice(0,50).flatMap(Object.keys))].slice(0,12):[];
 return <div className="fp-json-wrap"><div className="fp-json-head"><span>{title}</span><div className="fp-row" style={{gap:3}}>{table&&<><Button variant={`ghost small ${view==='json'?'active':''}`} onClick={()=>setView('json')}>JSON</Button><Button variant={`ghost small ${view==='table'?'active':''}`} onClick={()=>setView('table')}>Table</Button></>}<Button icon={copied?'Check':'Copy'} variant="ghost small" title="Copy JSON" onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify(value??null,null,2));setCopied(true);setTimeout(()=>setCopied(false),1500);}catch{setCopied(false);}}}/></div></div>{view==='table'&&table?<div style={{overflow:'auto',maxHeight:300}}><table className="fp-json-table"><thead><tr>{columns.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,50).map((r,i)=><tr key={i}>{columns.map(k=><td key={k}>{typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}</td>)}</tr>)}</tbody></table>{rows.length>50&&<small>Showing first 50 items.</small>}</div>:<pre className="fp-json-body">{JSON.stringify(value??null,null,2)}</pre>}</div>;
}
export const categoryColor={trigger:'#eabd78',ai:'#ae99ff',data:'#7fbbf3',logic:'#6cddb1',integration:'#f2ac7e',platform:'#7fbbf3',google:'#6cddb1',utility:'#9ca8c1'};
export function NodeIcon({definition,size=16}){return <span className="fp-node-icon" style={{'--node-accent':categoryColor[definition?.category]||'#a99aff'}}><Icon name={definition?.icon||'Workflow'} size={size}/></span>;}
export function downloadJSON(value,name){downloadText(JSON.stringify(value,null,2),name,'application/json');}
export function downloadText(text,name,type='text/plain'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
export function duration(ms){return !Number.isFinite(Number(ms))?'—':Number(ms)<1000?`${ms} ms`:`${(Number(ms)/1000).toFixed(1)} s`;}
export function dateLabel(value){if(!value)return 'Not run yet';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}
export async function api(url,options={}){const res=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options.headers}});let data;try{data=await res.json();}catch{throw new Error('The server returned an invalid response');}if(!res.ok){const error=new Error(data.error||'Request failed');error.status=res.status;throw error;}return data;}
