'use client';
import {useEffect,useState} from 'react';
import {Coins,RefreshCw,Save} from 'lucide-react';
const control='rounded-lg border border-line bg-surface2 px-3 py-2 text-sm text-paper';
async function api(options){const res=await fetch('/api/admin/automation-credits',{...options,headers:{'Content-Type':'application/json'},cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not load automation billing');return data;}
export default function AutomationCreditsAdmin({onChanged}){
 const [data,setData]=useState(null),[policy,setPolicy]=useState(null),[cost,setCost]=useState('1'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){setError('');try{const d=await api();setData(d);setPolicy(d.policy);}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function save(body){setBusy(true);setNotice('');setError('');try{await api({method:'PATCH',body:JSON.stringify(body)});setNotice('Pricing saved. New runs use the new prices; active runs keep their reserved price.');await load();await onChanged?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="space-y-5"><div className="rounded-2xl border border-line bg-surface p-5"><h2 className="flex items-center gap-2 text-lg font-semibold text-paper"><Coins size={20}/>Automation billing controls</h2><p className="mt-2 text-sm text-mist">Uses the existing user balance and plan allowance. Default: 1 credit per started node. Confirmed failures and unused steps are refunded. Retried attempts and per-item processing do not add extra node charges.</p>{error&&<p role="alert" className="my-3 text-sm text-red-400">{error}</p>}{notice&&<p role="status" className="my-3 text-sm text-signal">{notice}</p>}{policy&&<><div className="my-5 flex flex-wrap gap-5 text-sm text-paper"><label className="flex items-center gap-2"><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/>Enable automation charges</label><label className="flex items-center gap-2"><input type="checkbox" checked={policy.chargeTests} onChange={e=>setPolicy({...policy,chargeTests:e.target.checked})}/>Charge native test-mode nodes</label></div><p className="mb-3 text-xs text-mist">Mocked external calls, pinned test data, disabled nodes, skipped branches and notes are never charged. The browser-only sandbox remains an unbilled demo.</p><div className="flex flex-wrap items-end gap-3"><label className="text-xs text-mist">Maximum credits reserved per run<input className={`mt-1 block ${control}`} type="number" min="0" max="2000000" step="1" value={policy.maxRunCredits} onChange={e=>setPolicy({...policy,maxRunCredits:e.target.value})}/></label><button disabled={busy} className="flex items-center gap-2 rounded-lg bg-signal px-4 py-2 text-sm font-medium text-ink disabled:opacity-50" onClick={()=>save({action:'policy',enabled:policy.enabled,chargeTests:policy.chargeTests,maxRunCredits:Number(policy.maxRunCredits)})}><Save size={15}/>Save policy</button></div><div className="mt-5 border-t border-line pt-5"><h3 className="text-sm font-medium text-paper">Set every automation node to one price</h3><p className="my-2 text-xs text-mist">This replaces individual overrides and clears their scheduled changes. Document/PDF/TTS prices are not changed.</p><div className="flex flex-wrap gap-3"><input aria-label="All-node credit price" className={control} type="number" min="0" max="10000" step="1" value={cost} onChange={e=>setCost(e.target.value)}/><button disabled={busy} className={control} onClick={()=>{if(window.confirm(`Replace ALL automation node prices with ${cost} credits and clear scheduled automation prices?`))save({action:'set-all',cost:Number(cost),confirm:true});}}>Apply to all nodes</button></div></div></>}</div>
 {data&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Runs · last 7 days',data.totals.runs],['Credits used',data.totals.charged],['Credits returned',data.totals.refunded],['Uncertain receipts',data.totals.uncertain]].map(([label,value])=><div key={label} className="rounded-xl border border-line bg-surface p-4"><p className="text-xs text-mist">{label}</p><strong className="mt-2 block text-2xl text-paper">{value}</strong></div>)}</div><details className="rounded-2xl border border-line bg-surface p-5"><summary className="cursor-pointer text-sm font-semibold text-paper">Recent automation receipts ({data.receipts.length})</summary><button className={`my-3 flex items-center gap-2 ${control}`} onClick={load}><RefreshCw size={14}/>Refresh</button><div className="space-y-3">{data.receipts.map(r=><details key={r.key} className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-sm text-paper">{r.user?.email||'Deleted account'} · {r.label} · {r.charged} credits{r.uncertain?' · Needs review':''}</summary><p className="my-2 text-xs text-mist">{new Date(r.finishedAt).toLocaleString()} · {r.reserved} reserved / {r.refunded} returned · {r.key}</p>{r.units.map(u=><div className="flex justify-between gap-3 text-xs text-mist" key={u.key}><span>{u.label} · {u.status}</span><span>{u.status==='failed'?0:u.cost} cr</span></div>)}</details>)}</div><p className="mt-3 text-xs text-mist">Review uncertain external delivery before credit adjustment. Use the existing Admin → Users credit controls to grant a correction after active runs finish. Changes are audited; keep the receipt ID and reason in your support record.</p></details></>}
 </section>;
}
