'use client';
import {useEffect,useState} from 'react';
import {Icon,Button,Notice,request} from '@/components/ready-tools/ui';
import {Field} from '@/components/ready-tools/OptionsForm';
const TYPES=[['slackWebhook','Slack incoming webhook'],['discordWebhook','Discord webhook'],['telegram','Telegram bot token'],['bearer','API bearer token'],['header','API key in a custom header'],['basic','Basic authentication']].map(([value,label])=>({value,label}));
export default function ApiCredentials(){
 const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[remove,setRemove]=useState(null),[form,setForm]=useState({name:'',type:'slackWebhook',secret:'',headerName:'X-API-Key'});
 async function load(){setLoading(true);try{const value=await request('/api/flow-credentials');setItems(value.credentials||[]);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{await request('/api/flow-credentials',{method:'POST',body:JSON.stringify(form)});setForm({...form,name:'',secret:''});await load();setMessage('Credential saved. Return to your tool and refresh its connection list.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="rt-embedded"><section className="rt-settings-section"><h3>Automation connections & API credentials</h3><p>Save a secret once, then choose it by name in ready-made tools or advanced workflow nodes. These use the same encrypted credential store. A saved secret is not a verified service connection until a real request succeeds.</p>
  {error&&<Notice kind="error">{error}</Notice>}{message&&<Notice kind="success">{message}</Notice>}
  <div className="rt-credential-list">{loading?<p className="rt-muted">Loading saved credentials…</p>:items.length?items.map(c=><div className="rt-credential-item" key={c._id}><Icon name="KeyRound" size={18}/><div><strong>{c.name}</strong><small>{TYPES.find(t=>t.value===c.type)?.label||c.type} · secret hidden</small></div>{remove===c._id?<><Button variant="danger" disabled={busy} onClick={async()=>{setBusy(true);try{await request(`/api/flow-credentials/${c._id}`,{method:'DELETE'});setRemove(null);await load();setMessage('Credential removed. Update any tool or flow that used it.');}catch(e){setError(e.message);}finally{setBusy(false);}}}>Delete</Button><Button variant="ghost" onClick={()=>setRemove(null)}>Keep</Button></>:<Button icon="Trash2" variant="icon ghost" aria-label={`Delete ${c.name}`} onClick={()=>setRemove(c._id)}/>}</div>):<p className="rt-muted">No API credentials saved yet. Connected Google accounts are listed above.</p>}</div>
  <form onSubmit={save}><div className="rt-fields-grid"><Field label="Connection type" value={form.type} onChange={type=>setForm({...form,type,secret:''})} options={TYPES}/><Field label="Name you will recognize" value={form.name} onChange={name=>setForm({...form,name})} maxLength={80} placeholder="Marketing team Slack" required/></div>{form.type==='header'&&<Field label="Header name" value={form.headerName} maxLength={80} onChange={headerName=>setForm({...form,headerName})}/>}<Field label={form.type==='slackWebhook'||form.type==='discordWebhook'?'Webhook URL':'Secret value'} type="password" autoComplete="new-password" value={form.secret} maxLength={8192} onChange={secret=>setForm({...form,secret})} placeholder={form.type==='basic'?'username:password':'Paste your secret here'} required hint="Secrets are encrypted on the server and never returned by the list API. Keep ENCRYPTION_KEY unchanged."/><Button type="submit" icon={busy?'Loader2':'LockKeyhole'} className={busy?'rt-working':''} variant="primary" disabled={busy||!form.name.trim()||!form.secret.trim()}>{busy?'Saving…':'Save secure connection'}</Button></form>
 </section></div>;
}
