'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useWorkspace,Button,Icon,Notice} from '@/components/ready-tools/ui';
import {getTool} from '@/lib/readyTools/catalog.mjs';
import Toggle from './Toggle';
export default function ToolPreferencesTab(){
 const {workspace,update,error,loading}=useWorkspace(),[message,setMessage]=useState(''),[confirm,setConfirm]=useState(false);
 async function change(preferences){try{await update({action:'preferences',preferences});setMessage('Tool preferences saved.');}catch{setMessage('');}}
 return <div className="rt-embedded max-w-xl"><h2 className="font-display text-lg font-semibold text-paper">Tools & workflows</h2><p className="mt-1 text-sm text-mist">Control your ready-made tool experience from one place.</p>
  {error&&<div className="mt-4"><Notice kind="error">{error}</Notice></div>}{message&&<div className="mt-4"><Notice kind="success">{message}</Notice></div>}
  <section className="rt-settings-section"><h3>Appearance</h3><p>Ready-made tools, the workflow library and the advanced canvas all follow your main theme. There is no separate Flow Studio theme.</p><Link href="/dashboard/settings?tab=preferences" className="rt-button">Open theme preferences <Icon name="ArrowUpRight" size={14}/></Link></section>
  <section className="rt-settings-section"><h3>Result downloads</h3><p>Choose the primary download button for tables. All three formats remain available for each result.</p><label className="rt-field">Default format<select disabled={loading} value={workspace.preferences?.defaultExport||'csv'} onChange={e=>change({defaultExport:e.target.value})}><option value="csv">CSV</option><option value="xlsx">Excel (.xlsx)</option><option value="json">JSON</option></select></label></section>
  <section className="rt-settings-section"><h3>Activity & privacy</h3><Toggle checked={workspace.preferences?.rememberActivity!==false} onChange={value=>change({rememberActivity:value})} label="Remember recent tool activity" description="Saves the tool name, status, row count and time. Never saves uploaded files, input text or generated output."/><p>Turning this off stops new activity entries. Use Clear activity to remove existing entries. Tool-run request IDs and statuses are kept separately for up to seven days to prevent accidental replays; they do not contain message content. Credit receipts are retained separately for accounting, even when activity history is off.</p>{confirm?<div className="flex gap-2"><Button variant="danger" onClick={async()=>{try{await update({action:'clear-history'});setConfirm(false);setMessage('Recent activity cleared.');}catch{}}}>Confirm clear activity</Button><Button onClick={()=>setConfirm(false)}>Cancel</Button></div>:<Button icon="Trash2" onClick={()=>setConfirm(true)} disabled={!workspace.recent.length}>Clear activity ({workspace.recent.length})</Button>}</section>
  <section className="rt-settings-section"><h3>Saved option presets</h3><p>Presets remember column selections and tool options, not input content or account credentials. You can save up to 20.</p>{workspace.presets.length?workspace.presets.map(p=><div className="rt-preset-item" key={p.id}><div><strong>{p.name}</strong><small>{getTool(p.toolId)?.name||p.toolId}</small></div><Button icon="Trash2" variant="icon ghost" aria-label={`Delete preset ${p.name}`} onClick={async()=>{try{await update({action:'delete-preset',id:p.id});}catch{}}}/></div>):<p>No presets yet. Open a tool, adjust its options, and select Save options.</p>}</section>
  <section className="rt-settings-section"><h3>Accounts & credentials</h3><p>Google accounts, Slack/Discord webhooks, Telegram tokens and API credentials are managed in Connections. Tools select from these saved connections.</p><Link href="/dashboard/settings?tab=connections" className="rt-button">Manage connections <Icon name="ArrowUpRight" size={14}/></Link></section>
 </div>;
}
