'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ToolShell,Button,Notice,request,timeLabel} from '@/components/ready-tools/ui';
import {useSettings} from '@/lib/SettingsContext';
export default function CreditActivity(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);const {refresh:refreshSettings}=useSettings();
 async function load(){setLoading(true);setError('');try{setData(await request('/api/automation-credits'));await refreshSettings();}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 return <ToolShell title="Credit activity"><main className="rt-credit-history"><Link href="/dashboard/flows">← Back to ready-made tools</Link><h1>Every credit, accounted for.</h1><p>Your workflows and ready-made tools share your existing MultiMind balance. This page lists the latest 50 automation receipts, not chat, document or payment history.</p><Button icon="RefreshCw" disabled={loading} onClick={load}>{loading?'Refreshing…':'Refresh activity'}</Button>{error&&<Notice kind="error">{error}</Notice>}{data&&<><section className="rt-credit-panel"><div className="rt-credit-heading"><strong>Available credits</strong><b>{data.balance}</b></div><p>{data.reserved} reserved across {data.activeRuns} active runs. Unused reservations are returned at completion. Interrupted reservations are recovered after ten minutes when this page or another credit endpoint is opened.</p><Link href="/dashboard/settings?tab=billing">Plan & Billing →</Link></section>{!data.receipts.length&&<Notice>No automation charges yet. A receipt will appear after your first run.</Notice>}{data.receipts.map(r=><details className="rt-receipt" key={r.key}><summary><div><strong>{r.label||r.scope}</strong><small>{timeLabel(r.finishedAt)} · {r.status}</small></div><strong>{r.charged} credits used</strong></summary><p>{r.reserved} reserved · {r.refunded} returned{r.expiredUnused?` · ${r.expiredUnused} unused credits expired with the previous plan cycle`:''}</p>{r.uncertain&&<Notice kind="warning">An attempted step has an uncertain outcome. It may remain charged. Check the external destination and ask the administrator to review it before retrying.</Notice>}<div className="rt-credit-lines">{r.units.map(u=><div key={u.key}><span>{u.label} · {u.status}</span><strong>{u.status==='failed'?0:u.cost} cr</strong></div>)}</div><small>Receipt: {r.key}</small></details>)}</>}</main></ToolShell>;
}
