import test from 'node:test';
import assert from 'node:assert/strict';
import { safePath,resolveValue,parseJSON,compare } from '../../lib/flowPro/expressions.mjs';
import { normalizeGraph,toCanvas,topologicalLayers,validateGraph,autoLayout,exportWorkflow,importWorkflow,wouldCycle } from '../../lib/flowPro/graph.mjs';
import { nextSchedule } from '../../lib/flowPro/schedule.mjs';
import { isPublicAddress,validateHttpUrl } from '../../lib/flowPro/safeHttp.mjs';
import { NODE_TYPES } from '../../components/flows/nodeTypesConfig.js';
import { PRO_TEMPLATES,buildProTemplate } from '../../lib/flowPro/templates.mjs';
const n=(id,type='utility.log')=>({nodeId:id,type,position:{x:0,y:0},data:{}});
const e=(a,b)=>({edgeId:`${a}-${b}`,source:a,target:b});
test('safe expressions preserve object and number types',()=>{const ctx={previousOutput:{value:3,items:[1,2]},variables:{brand:'MultiMind'}};assert.equal(resolveValue('{{ $json.value }}',ctx),3);assert.deepEqual(resolveValue('{{ $json.items }}',ctx),[1,2]);assert.equal(resolveValue('Welcome to {{ $vars.brand }}',ctx),'Welcome to MultiMind');});
test('fallback expressions handle missing fields',()=>assert.equal(resolveValue('{{ $json.name ?? "Guest" }}',{previousOutput:{}}),'Guest'));
test('array paths are supported',()=>assert.equal(safePath({a:[{b:4}]},'a[0].b'),4));
test('prototype traversal is rejected',()=>assert.throws(()=>safePath({},'constructor.prototype'),/Unsafe/));
test('arbitrary expressions are rejected',()=>assert.throws(()=>resolveValue('{{ process.env.SECRET }}',{}),/Unsupported/));
test('JSON prototype pollution is rejected',()=>assert.throws(()=>parseJSON('{"__proto__":{"polluted":true}}'),/Unsafe/));
test('numeric comparisons do not use string ordering',()=>assert.equal(compare('100','gt','20'),true));
test('cycle detection rejects a back edge',()=>assert.throws(()=>topologicalLayers([n('a'),n('b')],[e('a','b'),e('b','a')]),/Circular/));
test('connection validation detects cycle before adding edge',()=>assert.equal(wouldCycle('b','a',[e('a','b')]),true));
test('dangling edge is rejected',()=>assert.throws(()=>topologicalLayers([n('a')],[e('a','b')]),/missing/));
test('duplicate node IDs are rejected',()=>assert.ok(validateGraph({nodes:[n('a'),n('a')],edges:[]},NODE_TYPES).some(i=>i.message.includes('Duplicate'))));
test('graph size is bounded',()=>assert.ok(validateGraph({nodes:Array.from({length:201},(_,i)=>n(`n${i}`)),edges:[]}).some(i=>i.message.includes('Maximum'))));
test('triggers cannot have incoming connections',()=>assert.ok(validateGraph({nodes:[n('a'),n('b','trigger.manual')],edges:[e('a','b')]},NODE_TYPES).some(i=>i.message.includes('trigger'))));
test('all templates pass structural validation',()=>{for(const t of PRO_TEMPLATES){const issues=validateGraph(buildProTemplate(t),NODE_TYPES);assert.deepEqual(issues.filter(i=>i.severity==='error'),[],t.id);}});
test('canvas and backend roundtrip without runtime state',()=>{const graph=buildProTemplate(PRO_TEMPLATES[0]);const canvas=toCanvas(graph);canvas.nodes[0].data.runtime={fake:true};const value=normalizeGraph(canvas);assert.equal(value.nodes[0].data.runtime,undefined);assert.equal(value.nodes[0].type,'trigger.webhook');assert.equal(value.edges[2].sourceHandle,'true');});
test('portable export omits credentials and pins',()=>{const graph=buildProTemplate(PRO_TEMPLATES[0]);graph.nodes[0].data.config.credentialId='private';graph.nodes[0].data.pinned=true;graph.nodes[0].data.pinnedData={token:'x'};const portable=exportWorkflow(graph);assert.equal(portable.nodes[0].data.config.credentialId,undefined);assert.equal(portable.nodes[0].data.pinnedData,undefined);assert.equal(importWorkflow(JSON.stringify(portable),NODE_TYPES).status,'draft');});
test('unsupported export versions are rejected',()=>assert.throws(()=>importWorkflow('{"schemaVersion":99,"nodes":[],"edges":[]}'),/newer/));
test('layout keeps valid finite node positions',()=>{const graph=autoLayout(buildProTemplate(PRO_TEMPLATES[0]));assert.ok(graph.nodes.every(n=>Number.isFinite(n.position.x)&&Number.isFinite(n.position.y)));});
test('Karachi daily schedule converts timezone correctly',()=>assert.equal(nextSchedule({time:'09:00',timezone:'Asia/Karachi'},new Date('2026-10-01T00:00:00Z')).toISOString(),'2026-10-01T04:00:00.000Z'));
test('weekly schedule uses the next matching day',()=>assert.equal(nextSchedule({frequency:'weekly',dayOfWeek:'mon',time:'09:00',timezone:'UTC'},new Date('2026-10-01T00:00:00Z')).toISOString(),'2026-10-05T09:00:00.000Z'));
test('invalid timezone and time are rejected',()=>{assert.throws(()=>nextSchedule({timezone:'Not/AZone'}));assert.throws(()=>nextSchedule({time:'29:99'}));});
test('SSRF protections block private/reserved destinations',()=>{for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','192.168.1.1','::1','fe80::1','::ffff:127.0.0.1'])assert.equal(isPublicAddress(ip),false,ip);assert.equal(isPublicAddress('8.8.8.8'),true);assert.equal(isPublicAddress('1.1.1.1'),true);assert.equal(isPublicAddress('2606:4700:4700::1111'),true);assert.equal(isPublicAddress('::ffff:8.8.8.8'),false);assert.equal(isPublicAddress('64:ff9b:1::1'),false);assert.equal(isPublicAddress('not-an-ip'),false);});
test('HTTPS allowlist rejects unknown hosts and unsafe URLs',()=>{assert.throws(()=>validateHttpUrl('https://evil.example',[]),/not approved/);assert.throws(()=>validateHttpUrl('http://example.com',['example.com']),/HTTPS/);assert.throws(()=>validateHttpUrl('https://a:b@example.com',['example.com']),/HTTPS/);assert.equal(validateHttpUrl('https://example.com/x',['example.com']).hostname,'example.com');});
test('portable export strips secrets from nested and JSON-text config',()=>{const graph=buildProTemplate(PRO_TEMPLATES[0]);graph.variables={brand:'MultiMind',apiKey:'no-share'};graph.nodes[0].data.config.headers='{"Authorization":"Bearer no-share","Accept":"application/json"}';graph.nodes[0].data.config.nested={password:'no-share',safe:1};const exported=exportWorkflow(graph);assert.equal(JSON.stringify(exported).includes('no-share'),false);assert.equal(exported.variables.brand,'MultiMind');assert.equal(JSON.parse(exported.nodes[0].data.config.headers).Accept,'application/json');});
test('legacy minute waits retain their duration during normalization',()=>{const old=n('old','logic.delay');old.data={config:{durationMinutes:5}};const normalized=normalizeGraph({nodes:[old],edges:[]});assert.equal(normalized.nodes[0].data.config.durationSeconds,300);});
